### PR TITLE
Added _dir_mode option to AttrTrees

### PR DESCRIPTION
**Pull request by jlstevens**
If you set ``t._dir_mode = 'user'`` on an ``AttrTree`` called ``t`` then only the keys added by the user are returned by \_\_dir\_\_ and tab-completed.

### CODE REVIEW

**Comment by jlstevens** [comment]
The tests are passing but I'm not sure this is ready to merge just yet. The last step involving ``__setattr__`` isn't being captured by ``__dir__``...

**Comment by jlstevens** [comment]
I'm not hugely happy with the last commit but it does seem to work. It also brings up another issue...shouldn't we be sanitizing the final identifier as well?

```python
tree = AttrTree()
tree.aaa.bbb.ccc = 3
u.Aaaa.Bbb.ccc
3
```

Note that ``ccc`` hasn't been capitalized.

**Comment by philippjfr** [comment]
I have no better suggestion and it looks fine to me. Happy to merge if you think it's ready.

**Comment by jlstevens** [comment]
I've done another push force, getting rid of the messing around with ``_terminals``.

I'll test it more to check ``__dir__`` works the way I expect and then if the tests pass, I think it can be merged.

**Comment by jlstevens** [comment]
I think this is ready to merge. In the end, I also added a small change to where the sanitizer is defined (makes it easier to override in subclasses).

**Comment by philippjfr** [comment]
Looks fine and worked for me. Merging.

**Pull request merged**
