### PR TITLE
Bokeh travis update

### PR DESCRIPTION
**Pull request by philippjfr**
Updated the bokeh version on travis to 0.12.5.

### CODE REVIEW

**Comment by jlstevens** [comment]
Great. I'll merge as soon as the tests pass.

**Comment by philippjfr** [comment]
Rebuilding test data shortly.

**Comment by jlstevens** [comment]
Odd Python 3 passed but lots of errors for 2.7...

**Comment by philippjfr** [comment]
Bokeh tests still only running on 2.7. The good news is that tests should become slightly faster again because it's now using the base64 encoding, the potential bad news is that I recall trying to update to 0.12.4 at some point and running into issues with the comparisons.

**Comment by jlstevens** [comment]
> Bokeh tests still only running on 2.7

I keep forgetting that! Anyway, I'll merge once the 2.7 tests pass.

**Comment by jlstevens** [comment]
Tests passing! Merging.

**Pull request merged**
