### PR TITLE
Added CSS class to logo block

### PR DESCRIPTION
**Pull request by philippjfr**
Adds a CSS class to the logo in the extension so it can be styled separately in the doc build.

### CODE REVIEW

**Comment by philippjfr** [comment]
Okay I've confirmed this works and doesn't affect the tests so I'm merging.

**Comment by jlstevens** [comment]
Could you paste the CSS rule here you used for 'logo-block' for future reference and in case anyone else needs it?

**Comment by philippjfr** [comment]
```css
div.logo-block {
	display: inline-block;
}
```

**Comment by jlstevens** [comment]
Thanks!

**Pull request merged**
