### PR TITLE
Updated search ordering when looking for holoviews.rc

### PR DESCRIPTION
**Pull request by jlstevens**
Addresses #1689.

### CODE REVIEW

**Comment by jlstevens** [comment]
@philippjfr Ready to merge - the test failure is just a transient.

**Comment by ceball** [comment]
Docs need to be updated: https://render.githubusercontent.com/view/ipynb?commit=516dfd701579506a440b1d5731fe734662d3034a&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f696f616d2f686f6c6f76696577732f353136646664373031353739353036613434306231643537333166653733343636326433303334612f6578616d706c65732f757365725f67756964652f496e7374616c6c696e675f616e645f436f6e6669677572696e672e6970796e62&nwo=ioam%2Fholoviews&path=examples%2Fuser_guide%2FInstalling_and_Configuring.ipynb&repository_id=19542768&repository_type=Repository#The-holoviews.rc-file

**Comment by ceball** [comment]
That link didn't work! I meant "The holoviews.rc file" in https://github.com/ioam/holoviews/blob/master/examples/user_guide/Installing_and_Configuring.ipynb

**Comment by jlstevens** [comment]
@ceball Thanks for the docs fix! Merging.

**Pull request merged**
