### PR TITLE
Graph.from_networkx method now extract node and edge attributes

### PR DESCRIPTION
**Pull request by philippjfr**
This PR will allow the Graph.from_networkx method to extract any attributes defined on the nodes and edges and also fixes a bug when trying to plot a Graph with no edges (i.e. only nodes).

- [x] Addresses https://github.com/ioam/holoviews/issues/2696
- [x] Fixes https://github.com/ioam/holoviews/issues/2711
- [x] Add unit tests

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to review/merge.

**Comment by soerendip** [comment]
I just cloned and installed holoviews. I still get the same error, when plotting without edges. Am I missing something? Clone the repo and `python setup.py install`?

**Comment by philippjfr** [comment]
What does ``hv.__version__`` report. Your example definitely seems to work for me:

screen shot 2018-05-23 at 12 02 02 am

**Comment by soerendip** [comment]
Ok, confirmed it works. Not sure what went wrong the last time.

**Comment by philippjfr** [comment]
Thanks for confirming!

**Pull request merged**
