### PR TITLE
Added example of using aliases to Columnar_Data tutorial

### PR DESCRIPTION
**Pull request by philippjfr**
Addresses https://github.com/ioam/holoviews/issues/1001, providing an example and explanation of using dimension aliases with a real dataset.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready for review, I've had to rebuild the test data so subsequent PRs will have to be rebased before their tests will pass.

**Comment by jbednar** [comment]
Looks good, thanks!

**Comment by philippjfr** [comment]
Thanks for the fix!

**Comment by jlstevens** [comment]
Looks good to me too. Happy to merge when the tests pass.

**Comment by jlstevens** [comment]
Tests are green. Merging.

**Pull request merged**
