### PR TITLE
Matplotlib aspect fixes

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/ioam/holoviews/issues/199, https://github.com/ioam/holoviews/issues/996 and https://github.com/ioam/holoviews/issues/1144. Plots in Layouts are no longer forced to square, semilog/loglog plots correctly apply aspects, and axis ranges are set after ticks.

### CODE REVIEW

**Comment by jlstevens** [comment]
Good to see three issues sorted with so little code! I guess the test data will now need to be updated...

**Comment by philippjfr** [comment]
Maybe, don't know yet, made a typo.

**Comment by philippjfr** [comment]
Continuous Coordinates
------------------------

Before:

image

Now:

image

Elements
---------

Before:

image

Now:

image


Sampling Data
---------------

Before:

image


Now:

image

I also still need to make sure that polar plots are forced to be square.

**Comment by jlstevens** [comment]
I think the original reason we tried to force everything to be square is that it made layouts easier.

**Comment by philippjfr** [comment]
>I think the original reason we tried to force everything to be square is that it made layouts easier.

Absolutely and without the layout fix that I added these examples would have really odd spacing I'm sure.

**Comment by philippjfr** [comment]
Ready to merge whenever, rebuilt the test data and PR build is passing.

**Comment by jbednar** [comment]
Excellent; thanks so much for fixing this previously very surprising behavior.  That said, even though these are surely reasonable to consider as bug fixes, they will affect the look and feel of existing notebooks, so they should be mentioned under compatibility changes.  Basically, if someone was relying on Layout to make things square, they will now have to force them to be square, and it will be helpful to mention how to do that in the release notes.

**Comment by jlstevens** [comment]
Sorry if I missed it but that is a good point - any easy way to restore the old behavior if necessary?

**Comment by philippjfr** [comment]
Not really no, except setting ``hv.plotting.mpl.RasterPlot = 'square'``, which will also affect plots not in Layouts.

**Comment by jlstevens** [comment]
Ok, then as Jim said it will need to be mentioned in the release notes.

The pr build is passing, is it ready to merge?

**Comment by philippjfr** [comment]
Yes, ready.

**Comment by jlstevens** [comment]
Great. Merging.

**Pull request merged**
