### PR TITLE
Add GridMatrix example to documentation

### PR DESCRIPTION
**Pull request by philippjfr**
As suggested in https://github.com/ioam/holoviews/issues/513, adds examples for the GridMatrix container to the Containers Tutorial. Shows two ways of using a GridMatrix, the first example looks like this, comparing a number of 1D distributions against each other:

image

and a GridMatrix of HoloMaps example showing 2D distributions individually and overlaid:

image

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good although the test data and website will still need to be rebuilt.

**Comment by philippjfr** [comment]
True, doesn't have to be merged right away. Can do it as we're nearing release.

**Comment by philippjfr** [comment]
Ready once tests are passing.

**Comment by philippjfr** [comment]
PR build passed, ready to merge.

**Comment by jlstevens** [comment]
Ok great!

**Comment by jlstevens** [comment]
Oh and you might want to trigger a website build..or have you already checked?

**Pull request merged**
