### PR TITLE
Fix code typo in example notebook

### PR DESCRIPTION
**Pull request by ceball**

### CODE REVIEW

**Comment by jlstevens** [comment]
I believe this address issue #1822.

@ceball It is helpful if you link to the issue you are addressing when opening new PRs if you know that there is an applicable issue...

**Comment by jlstevens** [comment]
I notice the tests are still broken... wonder if a transient got captured or some PR needed test data updating before getting merged. @philippjfr ?

**Comment by ceball** [comment]
> It is helpful if you link to the issue you are addressing when opening new PRs if you know that there is an applicable issue...

Sorry, didn't know about the issue you linked to. I was just trying to go through a few examples (using current hv master, which is proving frustrating...I'll get back to you about that).

**Comment by philippjfr** [comment]
>I notice the tests are still broken... wonder if a transient got captured or some PR needed test data updating before getting merged. @philippjfr ?

@jlstevens  I think your commit (https://github.com/ioam/holoviews/commit/021442d16278f0803addb613c8079eda6611f803) broke the tests by changing the hv.help output in the Options notebook.

**Comment by jlstevens** [comment]
@philippjfr Thanks for identifying that. I'm tempted to say we should change the notebook so that tests don't break when docstrings are fixed! Should I do that or regenerate the test data?

**Comment by philippjfr** [comment]
>Should I do that or regenerate the test data?

Either way you will have to regenerate test data now since removing it will itself be a change in it. I'll leave it up to you, it doesn't matter much since the old tutorial notebooks should go away once we find a way to test all our new materials.

**Comment by philippjfr** [comment]
I'm going to regenerate test data on this PR now and merge it since master should not be failing for this long. If someone wants to remove the help output from the Options tutorial to avoid an issue like this going forward open a new PR.

**Comment by philippjfr** [comment]
Going ahead and merging since the PR build passed.

**Pull request merged**
