### PR TITLE
Add BoundsX/BoundsY streams

### PR DESCRIPTION
**Pull request by jordansamuels**
* Core code is thanks to @philippjfr via gitter
* Added notebook examples and animated gifs
* Fixed mismatch in Bounds.bounds doc string

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks so much for those examples, they look great! We're not including the gifs directly in the repo at least for now. I'll upload them to assets.holoviews.org in the morning, then you can link to them from the notebook.

**Comment by jordansamuels** [comment]
@philippjfr understood.  In the end, I went with a different set of examples than what we discussed.

**Comment by jbednar** [comment]
Very nice!

**Comment by jlstevens** [comment]
Thank you! Those examples look great!

**Comment by philippjfr** [comment]
I have now uploaded these to our assets bucket, you can display them in the notebooks by linking to:

http://assets.holoviews.org/gifs/examples/streams/bokeh/boundsx_selection.gif
http://assets.holoviews.org/gifs/examples/streams/bokeh/boundsy_selection.gif

Once you've removed them from this PR and updated the notebooks, this is ready to merge. That will be our first user contributed gallery example, thanks again!

**Comment by philippjfr** [comment]
Thanks so much for adding this. I'll go ahead and merge now.

**Pull request merged**
