### PR TITLE
Fixed bokeh axis formatters for Overlays

### PR DESCRIPTION
**Pull request by philippjfr**
Fixed bug where wrong dimension formatter was applied.

### CODE REVIEW

**Comment by philippjfr** [comment]
Something wrong in Python 2, will fix in a bit.

**Comment by philippjfr** [comment]
Seems it was just transients ready to review/merge.

**Comment by jlstevens** [comment]
Looks fine although the old variable ``dim`` seems shorter and more convenient than ``dimension``. I am happy to merge now if you don't feel like implementing this minor suggestion.

**Comment by philippjfr** [comment]
Just merge it :wink:

**Pull request merged**
