### PR TITLE
Fixed colormapping of adjoined histogram in matplotlib

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes bug mentioned in #1663 

image

Histogram now correctly determines if it should be colormapped or not.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good - this issue has been around for quite a while I think. Any way to add a unit test to make sure there is no regression?

**Comment by jlstevens** [comment]
@philippjfr Happy to merge when the tests are green. I assume display data needs updating?

**Comment by philippjfr** [comment]
Should pass now I made a small fix. Ready to merge once it does.

**Comment by philippjfr** [comment]
Okay ready now.

**Comment by jlstevens** [comment]
I suppose this will be tested once we finally have notebook tests running again. Merging.

**Pull request merged**
