### PR TITLE
Followup fixes for HeatMap generalization

### PR DESCRIPTION
**Pull request by philippjfr**
Realized I hadn't pushed some final fixes in #849, ready to merge once tests pass.

### CODE REVIEW

**Comment by jlstevens** [comment]
Nevermind!

**Comment by jlstevens** [comment]
Hit the wrong button again! Waiting for the tests...

**Comment by philippjfr** [comment]
Also for reference here's how HeatMap now deals with numeric data:

screen shot 2017-01-09 at 6 39 15 pm

**Comment by jlstevens** [comment]
@philippjfr Maybe we should have a section of contrib for such examples? Though I suppose it would be hard to get mybinder (or any other approach) to compare between versions/commits...

**Comment by jlstevens** [comment]
Tests have now passed. Merging.

**Pull request merged**
