### PR TITLE
Fixed clip parameter on Violin

### PR DESCRIPTION
**Pull request by philippjfr**
The clip option on ViolinPlot made no sense as it would actually override any custom ranges.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good to me. Is ``clip`` a parameter unique to ``ViolinPlot``? Is so, I am happy to merge now, otherwise I hope this parameter is consistent with any other parameters called ``clip``. And if it is the former, I suppose ``clip`` does sounds like a very general parameter name that we might want for something more general than just violin plots?

**Comment by philippjfr** [comment]
It is in fact unique as of right now but it would also be useful to have on Distribution plots. Would do that in a new PR though.

**Comment by jlstevens** [comment]
Ok. Sounds like ``clip`` will apply to multiple plot types in future. That said, the notion of clipping to the min/max seems like something more general than even just the statistical plots...

**Comment by philippjfr** [comment]
>That said, the notion of clipping to the min/max seems like something more general than even just the statistical plots...

Hmm, in those cases you can select on the data, but for statistical plots you might want to include outliers in the density calculation but not sample the density estimate beyond a certain clipping range. So I'm not in favor of adding a clip parameter to other plot types.

**Comment by jlstevens** [comment]
Ok. Given that you seem happy with this parameter name, I'll go ahead and merge.

**Pull request merged**
