### PR TITLE
Layout, overlay and grid of a HoloMap now reduces all key dimensions by default.

### PR DESCRIPTION
**Pull request by vascotenner**
This makes it possible to easily get an overview of the contents of a holomap, as discussed in #254

### CODE REVIEW

**Comment by vascotenner** [comment]
Should this be mentioned in the docstrings?

**Comment by jlstevens** [comment]
> Should this be mentioned in the docstrings?

Yes I think a docstring is needed and as I mentioned in the issue, I am in favour of this change.

**Comment by philippjfr** [comment]
If you look at Line 519 in core/dimension.py, there is a method called ``_valid_dimensions``, instead of duplicating this three times in each of these method you could replace these lines:

```
        if not dimensions:
            return dimensions
```

with your changes:

```
if dimensions is None:
    dimensions = self.kdims
```

While you're at it you could also rename the method to ``_validate_kdims``. If you want I can make these changes quickly and push them but I'm of course also happy for you to amend this PR, in which case I'll merge it immediately.

**Comment by vascotenner** [comment]
I implemented the philippjfr's suggestion.

In core/element.py line 126, there is some code that uses the _valid_kdims metho, but I do not understand how it works, but I guess it is broken by this commit

**Comment by philippjfr** [comment]
Seems fine, merging now.

**Pull request merged**
