### PR TITLE
Fixing constant dimensions

### PR DESCRIPTION
**Pull request by philippjfr**
This PR fixes various issues with constant dimensions, in particular it ensures the the default call to .dimensions no longer returns the constant dimensions, which caused a wide range of issues.

### CODE REVIEW

**Comment by jlstevens** [comment]
The change looks fine but I am slightly concerned that it pushes constant dimensions to the side. We haven't thought too deeply about constant dimensions but there are cases where they are definitely useful.

I'm also worrying why you didn't just leave ``_dim_groups`` alone and then exclude 'cdims' and 'constant_dimensions' inside ``dimensions`` when ``selection='all'`` (the default). Does removing 'cdims' from ``_dim_groups`` have another effect you need in this fix?

**Comment by philippjfr** [comment]
I'll readd them to dim_groups but until we've thought them through properly returning by default breaks all kinds of assumptions. We should open an issue to discuss how they should actually be used and then integrate them properly.

**Comment by jlstevens** [comment]
Ok great! I'll merge as soon as the tests pass.

**Comment by jlstevens** [comment]
The tests are passing now. Merging.

**Pull request merged**
