### PR TITLE
SideHistogram supports coloring weighted average

### PR DESCRIPTION
**Pull request by philippjfr**
The adjoined histograms support coloring by a dimension on the main plot, but they also used to support coloring weighted histograms, which take the average in bins along the x- and y-axis. Coloring by the mean weighted value produces plots like this (matplotlib already handles this):

```python
x,y = np.mgrid[-50:51, -50:51] * 0.1

img = hv.Image(np.sin(x**2+y**2), bounds=(-1,-1,1,1))

hmap = hv.HoloMap({phase: img.clone(np.sin(0.1*x**2+0.1*y**2+phase))
                   for phase in np.linspace(0, np.pi*2, 6)}, kdims=['Phase'])
hmap.hist(num_bins=100, dimension=['x', 'y'], weight_dimension='z', mean_weighted=True)
```

weighted_avg_hist

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge, missing test data doesn't matter as no tests have changed.

**Comment by jlstevens** [comment]
Looks good! 

I was expecting to see a much longer and more complicated diff given the description. Given that this is simply exposing functionality from the backend, I am happy to merge this PR.

That said, does this work in Bokeh if matplotlib isn't available? I'm still a little confused as the diff mostly seems to address color mapping issues and I don't yet see where the ``weight_dimension='z', mean_weighted=True`` arguments get supported (in a backend agnostic way).

**Comment by philippjfr** [comment]
>That said, does this work in Bokeh if matplotlib isn't available? I'm still a little confused: the diff mostly seems to address color mapping issues and I don't yet see where the weight_dimension='z', mean_weighted=True arguments get supported (in a backend agnostic way).

The histogram operation supports these already. It's just that bokeh didn't grab the correct color mapper in this case.

**Comment by jlstevens** [comment]
> The histogram operation supports these already. It's just that bokeh didn't grab the correct color mapper in this case.

Thanks for clarifying. Merging.

**Pull request merged**
