### PR TITLE
Sort `values` in hv.Dimension

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by jlstevens** [comment]
I think this makes sense - sliders require an ordering to work (by definition) so sorting seems sensible.

Happy to merge when the tests pass.

**Comment by philippjfr** [comment]
PR build passed. @jlstevens should we merge?

**Comment by jlstevens** [comment]
What happened to the push build?

image

Otherwise I am happy to see this PR merged (given the tests passed).

**Comment by philippjfr** [comment]
Only branches get push builds.

**Pull request merged**
