### PR TITLE
Update plotly/raster.py to fix Raster for plotly

### PR DESCRIPTION
**Pull request by thoth291**
This should fix an issue with Raster for plotly backend which was reported here:
https://github.com/ioam/holoviews/issues/2821

### CODE REVIEW

**Comment by philippjfr** [comment]
LGTM, will merge when tests pass.

**Comment by thoth291** [comment]
if ci would be so kind and report which of the notebooks are failing to be tested - I would probably take a look at it...
Situation is getting even more strange given that this test failure is Python3 sensitive. Python2 test is passed with no issues.

**Comment by philippjfr** [comment]
Don't worry about it, don't think it has anything to do with your change.

**Comment by philippjfr** [comment]
I'll merge and fix it up later if the issue persists.

**Pull request merged**
