### PR TITLE
Updated style with new show_frame settings 

### PR DESCRIPTION
**Pull request by jlstevens**
Talking to @philippjfr we decided that only raster types, path types and vectorfields should have frames.

### CODE REVIEW

**Comment by philippjfr** [comment]
What about Scatter and Points? They share a plotting class so setting it on the class won't be sufficient to give Points a frame and Scatter none.

**Comment by jlstevens** [comment]
> What about Scatter and Points? 

I think that is the only one that needs to be set with the options system and not at the class level. I'll push that fix now.

**Comment by jlstevens** [comment]
@philippjfr Looks like the tests will go green. Ready for final review/merge.

**Comment by philippjfr** [comment]
Looks good will merge shortly.

**Pull request merged**
