### PR TITLE
Correctly sanitize HeatMap and Bar plot CDS columns

### PR DESCRIPTION
**Pull request by philippjfr**
When ColumnDataSource columns contain special characters or spaces the column names have to be sanitized. This PR ensures the BarPlot and HeatmapPlot implementations correctly sanitize the column names.

### CODE REVIEW

**Comment by jlstevens** [comment]
Will need some unit tests and I wish we needed to sanitize in fewer places. Otherwise looks good.

**Comment by philippjfr** [comment]
I'll make sure to add some unit tests, but it appears bokeh notebook tests were already affected, here's a Bokeh_Elements error:

    {'new_value': u'u'Car_occupants', 'old_value': 'Car occupants'}

**Comment by philippjfr** [comment]
Added some unit tests, will rebuild the test data, then it's ready to merge.

**Comment by jlstevens** [comment]
Tests are passing along with the new unit tests. Merging.

**Pull request merged**
