### PR TITLE
Suppress warnings about deprecated rcParams in matplotlib>=3.0

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes https://github.com/ioam/holoviews/issues/2963

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by philippjfr** [comment]
Merging this myself since the warnings are driving me crazy and it's a pretty straightforward fix.

**Comment by GbengaOdesanmi** [comment]
Please ho to fixe this error

matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

**Comment by philippjfr** [comment]
It should be fixed in the next release, coming next week.

**Comment by GbengaOdesanmi** [comment]
Please how do i fix this, thanks in advance
 
python -m baselines.her.experiment.plot /tmp/openai-2018-12-19-12-21-56-179878
/home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.6/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

**Pull request merged**
