### PR TITLE
Fixed ticks in 'bare' x/yaxis plot option in matplotlib

### PR DESCRIPTION
**Pull request by philippjfr**
Relatively minor fix to tick labels that changes a few display tests.

### CODE REVIEW

**Comment by jlstevens** [comment]
Ok. This would be a good place to test the new workflow for updating reference data! Should be ready soon...

**Comment by philippjfr** [comment]
Ready for merge. Very minor fix, which unfortunately will touch quite a bit of reference data.

**Comment by jlstevens** [comment]
> Very minor fix, which unfortunately will touch quite a bit of reference data.

For this reason, I would like to merge a few other PRs first to make sure reference data is updated as we expect...

**Comment by jlstevens** [comment]
The change looks simple so I am happy to merge. As I understand it, we don't expect the ``push`` build to pass but the ``pr`` build is passing and that is what matters. Merging.

**Pull request merged**
