### PR TITLE
Workaround for datetime streaming bug in bokeh

### PR DESCRIPTION
**Pull request by philippjfr**
Very ugly workaround for https://github.com/bokeh/bokeh/issues/7587 in bokeh datetime streaming.

### CODE REVIEW

**Comment by stonebig** [comment]
so my code with bokeh-0.12.5.dev1 will break  also ? would it be possible to include it in the test ?

**Comment by philippjfr** [comment]
>so my code with bokeh-0.12.5.dev1 will break also ? would it be possible to include it in the test ?

Probably a good idea.

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by philippjfr** [comment]
Looks like this change will require pinning to bokeh>=0.12.14, which also affects 1.9.5 since I ported this change there.

**Comment by jlstevens** [comment]
> Looks like this change will require pinning to bokeh>=0.12.14...

Are you going to pin bokeh in this PR? I would also like to see an issue to remove this hack once it is fixed in bokeh to make sure we remove this code when we can.

Otherwise, happy to merge.

**Comment by philippjfr** [comment]
>I would also like to see an issue to remove this hack once it is fixed in bokeh to make sure we remove this code when we can.

Unless we want to remove support for bokeh 0.12.14 we can't really delete this.

**Comment by jlstevens** [comment]
> Unless we want to remove support for bokeh 0.12.14 we can't really delete this. 

We will be happy to remove support for bokeh 0.12.14 *eventually* so I would still file an issue. Maybe assign it to the 2.0 milestone.

**Comment by jlstevens** [comment]
Looks good. Merging.

**Pull request merged**
