### PR TITLE
Typo in link in documentation

### PR DESCRIPTION
**Pull request by vascotenner**

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks! I'll restart the tests now...I assume it is a transient error...

**Comment by philippjfr** [comment]
Tests are failing due to some unrelated scipy error, may have to pin the version.

```
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

**Comment by jbednar** [comment]
Or install gfortran?

**Comment by philippjfr** [comment]
Should be installed automatically when installing scipy/numpy with conda. I assume it's a version incompatibility issue because we've pinned the numpy version for matplotlib compatibility. We really have to sort out the version compatibility mess on travis, may involve filing a bug on conda.

**Comment by philippjfr** [comment]
I'm going to go ahead and merge. Tests on master are failing anyway until we sort out the mess on Travis.

**Pull request merged**
