### PR TITLE
Bug fixes for single column GridPlots and titles

### PR DESCRIPTION
**Pull request by philippjfr**
As title says provides bug fixes to allow single column GridPlots and to fix an unreferenced variable bug when updating GridPlot titles.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks like a nice, small change. I'm happy to merge it if you think it is ready.

**Comment by philippjfr** [comment]
It is yea, but something is up with the test data. May just have to rerun it.

**Comment by jlstevens** [comment]
The pr build passed so at a glance it looked ready. If the issue is with transients, a passing pr build would require the same set of errors to happen twice (fairly unlikely) so now I'm wondering what is up!

**Comment by philippjfr** [comment]
Ah, odd, I think I must have restarted the PR build yesterday as the entire Elements tutorial failed the first time.

**Comment by philippjfr** [comment]
Given that the PR build is now passing, you can merge whenever.

**Comment by jlstevens** [comment]
Ok great! Merging.

**Pull request merged**
