### PR TITLE
Improved abbreviated exception and traceback processing

### PR DESCRIPTION
**Pull request by jlstevens**
PR to address #507 which eliminates the hackish code that didn't work particularly well and replaces it with a more targeted solution. We now need to use the ``abbreviated_exception`` context manager in the plotting code as appropriate. All other exceptions and tracebacks now remain unaffected.

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good. I think this behavior will be much better than before.

**Comment by jlstevens** [comment]
One issue with this approach is that Python users outside the notebook will occasionally see ``AbbreviatedExceptions`` instead of the normal ones.

Maybe I should just add ``__str__`` and ``__repr__`` methods to the new exception class to make it clear the original exception and traceback are inside?

**Comment by jlstevens** [comment]
I've added the ``__str__`` method, so here is something a pure Python user might see something like this:

```
AbbreviatedException: Abbreviated ValueError: Colormap jetz is
not recognized. Possible values are: Accent, Accent_r, Blues,
Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap,
CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, ...

To view the original traceback, catch this exception and access
the traceback attribute.
```

The traceback above will lead up to the point where the context manager is called.

**Comment by jlstevens** [comment]
If the tests pass and you are happy with this, please merge. I do think this system will be a lot better!

**Comment by jlstevens** [comment]
This new exception is related to ``BackendError`` introduced in #366. I think the new approach is better but I've tried to support the one place where ``BackendError`` was used.

**Comment by jlstevens** [comment]
I think it is actually ready to merge once the tests pass. @philippjfr Are you happy with these changes?

**Comment by jlstevens** [comment]
The pr build is passing while the push build has been consistently failing. As the pr build is what counts, please merge if you think it is ready.

**Comment by philippjfr** [comment]
Looks good to me. I think I'll open a separate issue to remind us to go through our code and make a concerted effort to raise more and better exceptions.

**Pull request merged**
