### PR TITLE
Fixed flakes in mpl and plotly backend

### PR DESCRIPTION
**Pull request by jlstevens**
This PR fixes the remaining flakes issues raised with:

```
flake8 --ignore=E,W,F999  .
```

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks fine, will merge when tests passes.

**Comment by jlstevens** [comment]
I might as well do the tests in this PR as well. So don't merge just yet...

**Comment by jlstevens** [comment]
@philippjfr  Read to merge once the tests pass.

**Comment by jlstevens** [comment]
And don't forget to do a squash merge this time!

**Comment by philippjfr** [comment]
Looks good and the PR build passed, merging.

**Pull request merged**
