### PR TITLE
Bokeh adjoined histogram adds support for live colormapping

### PR DESCRIPTION
**Pull request by philippjfr**
An adjoined histogram in bokeh now automatically shares the color mapper of whatever plot it is adjoined to it and adds a ``box_select`` tool with a ``CustomJS`` to update that colormapper based on the current selection. Since this callback is pure JS this will also work on static export.

dynamic_colormap

### CODE REVIEW

**Comment by jbednar** [comment]
Cool!

**Comment by philippjfr** [comment]
Based off https://github.com/ioam/holoviews/pull/927, so that should be merged first.

**Comment by jbednar** [comment]
#927 is merged, so can this be merged now?

**Comment by philippjfr** [comment]
Yes, I just have to rebuild test data first (because you broke it :smile:).

**Comment by jbednar** [comment]
Is the test data in github?  Seems easier just to edit that one character.

**Comment by jlstevens** [comment]
PR #927 has now been merged and this functionality is certainly very nice (especially as it doesn't need a live server). My only concern is that it doesn't seem hugely intuitive to me to use the box select on the side histogram. Other than that, I am happy to merge.

**Comment by jbednar** [comment]
The box select tool seems very intuitive to me, in terms of mouse clicking; it's just that ideally the visual representation would not be a box but a range of histogram bins.  I.e., the same clicks should do the same thing, but the selected area should show bins, not portions of bins, ideally.  Still, that seems like a nicety that could be added someday, and shouldn't hold up this PR.

**Comment by jlstevens** [comment]
It is certainly nice functionality! Merging.

**Pull request merged**
