### PR TITLE
Adding a grid based xarray data interface 

### PR DESCRIPTION
**Pull request by philippjfr**
As the title suggests this PR adds an xarray interface, which will allow working with large gridded datasets. It is not quite complete, so should not be merged yet, but it's functional and there are just a few more issues to iron out before I can add unit tests and merge it.

What's still missing?

- [ ] Multi-dimensional aggregate/reduce
- [x] Add dimension support
- [ ] Reindex support for dropping constant dimensions
- [x] Unit tests

### CODE REVIEW

**Comment by jlstevens** [comment]
I would be interested in helping you finish off this PR to learn a bit more about xarray. Though there seems to be merge conflicts now?

**Comment by philippjfr** [comment]
I can resolve the merge conflicts now. As for this PR, it might be worth waiting until a multi-dimensional groupby has been merged into xarray (https://github.com/pydata/xarray/pull/818).

**Comment by philippjfr** [comment]
The multi-dimensional groupby was just merged and I think Stephan is targeting an xarray release for next week, so should we try to get this into 1.5.1?

**Comment by jlstevens** [comment]
> The multi-dimensional groupby was just merged and I think Stephan is targeting an xarray release for next week, so should we try to get this into 1.5.1?

If the interface is complete and we can support the upcoming xarray release (I suppose we can test against a dev version) then yes, I think it would be good to get in for 1.5.1.

**Comment by jbednar** [comment]
Sounds good.  It would be great to be able to promote this feature at SciPy!

**Comment by philippjfr** [comment]
Deferring support for aggregate, sample, reduce and reindex. About to add tests and then ready to merge.

**Comment by jlstevens** [comment]
As the PR build passed, looks good and I'll merge it now.

**Pull request merged**
