### PR TITLE
fix typos "{X,Y}Bounds" -> "Bounds{X,Y}"

### PR DESCRIPTION
**Pull request by jordansamuels**

### CODE REVIEW

**Comment by jbednar** [comment]
Looks like an obvious and correct fix; not sure why there is a Py3 test error at https://travis-ci.org/ioam/holoviews/jobs/252146034#L1608 .

**Comment by jordansamuels** [comment]
Hmm, now coverage is failing in addition to continuous.  Are we discovering build issues?  In any case, this is super low priority, so we can wait.

**Comment by philippjfr** [comment]
@jordansamuels Annoyingly we have some transient errors in our builds. Usually restarting it will resolve those, which I've just done.

**Comment by jlstevens** [comment]
@jordansamuels Thanks for these fixes!

The tests are passing now. Merging.

**Pull request merged**
