### PR TITLE
Remove all bokeh backward compatibility code

### PR DESCRIPTION
**Pull request by philippjfr**
As we decided in #1949 we are going to drop compatibility with versions of bokeh older than 0.12.10 in the next release. This PR removes all code that handles backward compatibility for older versions.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge once tests pass.

**Comment by philippjfr** [comment]
Yay, 80% coverage!

**Comment by jlstevens** [comment]
Looks good. 

We do need to issue a clear error when the bokeh version is an old, unsupported one. Otherwise we will get tons of issues from users who haven't recently upgraded bokeh!

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jlstevens** [comment]
Looks good to me. Merging.

**Pull request merged**
