### PR TITLE
Renamed DynamicMap 'closed' mode to 'bounded'

### PR DESCRIPTION
**Pull request by jlstevens**
PR title says it all. 

As far as I know, we are aware of (and can update) all code that may have used ``DynamicMap`` up until this point...

### CODE REVIEW

**Comment by jlstevens** [comment]
Mathematically 'closed' and 'open' isn't the same as 'bounded' and 'unbounded'. I've left 'open mode' alone as I think 'unbounded' is too long and 'open' has fairly natural semantics (as opposed to 'closed' versus 'bounded'). 

@jbednar @philippjfr Any thoughts on this? This is our last chance to change it!  I think 'counter' mode is unproblematic unless you feel there is something better. Maybe 'step' mode?

**Comment by philippjfr** [comment]
Sounds clearer to me and there isn't much backward compatibility to worry about. I'll merge unless @jbednar raises any objections in the next few minutes.

**Comment by jlstevens** [comment]
Yes, please merge as I have another PR that will operate on the same file.

**Comment by philippjfr** [comment]
Okay, too late for objections :) I'll merge

**Pull request merged**
