### PR TITLE
Allowed using xarray with dask arrays

### PR DESCRIPTION
**Pull request by philippjfr**
XArray supports wrapping around dask arrays. Generally this doesn't cause any issues but the ``dimension_values`` method should always return an in-memory NumPy array so this PR is sufficient for us to have full support for dask arrays via xarray.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good! 

I had a prototype line like this once before but supporting dask via xarray makes sense. My main comment is that a few unit tests would be nice (marked optional and dask would need to be available on travis).

**Comment by philippjfr** [comment]
I'm now running all existing Dataset tests against an xarray dataset containing dask arrays. Those 60 unit tests should cover it pretty well.

**Comment by jlstevens** [comment]
I'll merge when the tests go green.

**Comment by philippjfr** [comment]
Hold off on merging, found some issues.

**Comment by philippjfr** [comment]
Okay, now fixed. Ready to merge once tests pass.

**Comment by jlstevens** [comment]
Tests have passed. Merging.

**Pull request merged**
