### PR TITLE
Trisurface renamed to TriSurface

### PR DESCRIPTION
**Pull request by jlstevens**
The branch is misnamed after deciding that ``TriMesh`` was not the inconsistent name but ``Trisurface`` was.

### CODE REVIEW

**Comment by jlstevens** [comment]
@philippjfr Not sure there is much more to this PR other than having you check that the plotly TriSurface/Trisurface works for you (I can't test it because of some odd webgl error!)

**Comment by philippjfr** [comment]
There are demo notebooks, which haven't been updated:

http://holoviews.org/gallery/demos/matplotlib/trisurf3d_demo.html
http://holoviews.org/gallery/demos/plotly/trisurf3d_demo.html

**Comment by jlstevens** [comment]
Thanks..I'll fix those shortly.

**Comment by jlstevens** [comment]
That should be the rest of them. Happy to merge when the tests pass?

**Comment by jlstevens** [comment]
There are two failures that look like they will require the test data to be updated.

**Comment by philippjfr** [comment]
>There are two failures that look like they will require the test data to be updated.

Seems likely if you updated the ``group``.

**Comment by jlstevens** [comment]
I have now updated the test data.

**Comment by philippjfr** [comment]
PR build passing, merging.

**Pull request merged**
