### PR TITLE
Correctly set batched plot options

### PR DESCRIPTION
**Pull request by philippjfr**
Correctly respect the plot options set on the batched elements. Previously inherited all plot options from the NdOverlay, which a) could cause unsupported parameters being set and b) ignored plot options set on the Element. This appropriately combines the plot options from set on the NdOverlay and Element plot.

### CODE REVIEW

**Comment by jlstevens** [comment]
Is this ready for review?

**Comment by jbednar** [comment]
It certainly sounds like an improvement, and I'd be in favor of merging.

**Comment by philippjfr** [comment]
Yes, ready to review/merge.

**Comment by jlstevens** [comment]
I notice this is implemented on ``GenericElementPlot`` but the tests have passed, the changes look reasonable so I think it is all ok. Merging.

**Pull request merged**
