### PR TITLE
Operation fixes

### PR DESCRIPTION
**Pull request by philippjfr**
A number of small fixes for existing operations:

1) Disable the ``group`` being inherited from composite types as would sometimes occur when applying operations to an NdOverlay resulting in Element being labeled "NdOverlay".

2) Hide warning in ``datashade`` operation when shading a categorical aggregate.

3) Removed the adjoin parameter to ``histogram`` operation, it continually annoys me because the ``hist`` method has to handle the adjoining itself anyway and having the operation return an adjoined object is a) weird and b) actually breaks if you're trying to apply the operation to a HoloMap or other kind of composite object.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to review.

**Comment by jlstevens** [comment]
Looks good though I am worried about backwards compatibility implications for point 3. I agree with your rationale for removing the adjoin option but is anyone using it?

How about checking if ``adjoin`` is in the kwargs and issuing a useful exception message with some advice? Maybe something like 'Adjoin option deprecated: use the << operator to explicitly adjoin output histogram'?

**Comment by philippjfr** [comment]
>How about checking if adjoin is in the kwargs and issuing a useful exception message with some advice? Maybe something like 'Adjoin option deprecated: use the << operator to explicitly adjoin output histogram'?

I suspect people were sufficiently discouraged from using. I'm happy to add the exception but in fixing it I realized the operation itself was fairly useless in all kinds of ways, auto-ranging was disabled for instance so without supplying an explicit ``bin_range`` or None you'd get a histogram ranging from 0 to 1.

**Comment by jlstevens** [comment]
Ok. In that case, I am happy to merge...although the pr build does seem to have failed right now...

**Comment by philippjfr** [comment]
One of the many transients we're struggling with again, about 1/4 builds fail.

**Pull request merged**
