### PR TITLE
Allows plotting GridSpaces inside Layouts in bokeh

### PR DESCRIPTION
**Pull request by philippjfr**
This PR makes the bokeh ``GridPlot`` and ``LayoutPlot`` fully composable so you can now plot multiple grids together. Here's two grids and a regular element in a layout:

```python
%%opts Image [height=260]
(hv.GridSpace({(i, j): hv.Curve(range(i+j)) for i in range(1, 3) for j in range(2,4)}) +\
 hv.GridSpace({(i, j): hv.Curve(range(i+j)) for i in range(1, 3) for j in range(2,4)}) +
 hv.Image(np.random.rand(10,10)))
```

screen shot 2017-02-05 at 11 53 08 pm

The ``Composing_Data`` tutorial now also works for both matplotlib and bokeh:

screen shot 2017-02-06 at 2 48 12 am

Related: https://github.com/ioam/holoviews/issues/381

### CODE REVIEW

**Comment by philippjfr** [comment]
Hmm, the drop in coverage is odd. Will have to look into it.

**Comment by philippjfr** [comment]
Now fixed, ready to review/merge.

**Comment by jlstevens** [comment]
Unfortunately there now seem to be merge conflicts. Happy to merge once that is resolved and the tests have passed.

**Comment by philippjfr** [comment]
First time I resolved merge issues directly on GitHub, ready to merge when passing again.

**Comment by jlstevens** [comment]
Looks good and the tests are passing. Merging.

**Pull request merged**
