### PR TITLE
Replaced usage of deleted stack_area operation

### PR DESCRIPTION
**Pull request by philippjfr**
``stack_area`` was removed, replaced with ``Area.stack``

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks! 

I'm guessing these files didn't yet exist in the repo (or on that branch) when I grepped to make this change.

**Comment by philippjfr** [comment]
I'm pretty sure they must have been around at that point. Simple fix though.

**Comment by philippjfr** [comment]
No need to wait on tests tbh, not tested yet anyway.

**Comment by jlstevens** [comment]
> I'm pretty sure they must have been around at that point. 

Odd. I'm sure I grepped for that string. Anyway, merging.

**Pull request merged**
