### PR TITLE
Alias utility update

### PR DESCRIPTION
**Pull request by jlstevens**
This PR aims to address #1427. I realize we don't yet have a solution everybody is happy with but I think this is worth updating while the utility still exists.

Here is an example of it in use:

image

For this example it doesn't do much but if you have a long notebook that reuses dimensions/groups/labels constantly, I think this utility really pays off, making everything more succinct and organized. It means you can specify the definitions once at the top, making the rest of the notebook more succinct.

Once we do find a good solution to defining dimensions and sanitized groups/labels without awkward repetition we should document it and probably remove the dimension preset system.

### CODE REVIEW

**Comment by jlstevens** [comment]
In the end, I decided to rename ``Aliases`` to ``Dims`` and focus on dimension aliases only:

image

Unless I add something for tuple aliases, this means we offer nothing to help with sanitized group/label aliases.

**Comment by jbednar** [comment]
Would something like this work as a more general approach, not specific to Dimensions or groups or labels, but just to things that you might want to look up easily?

```
class Aliases(object):
"""
Helper class useful for defining aliases, which are 
Python identifiers that expand either to a named
object or to an arbitrary Python string.

Sample usage:

``
d = Aliases(hv.Dimension('female_weight', unit='kg', range=(0,None)),
            male_weight='Body weight of male participants',
            mh=hv.Dimension('male_height', unit='kg', range=(0,None)))
Curve(data, kdims=[d.female_weight], vdims=[d.mh])
``

Here `female_weight` is passed as a positional argument, and is thus
addressed by its `name` attribute, while the others are addressed
by the specified keyword.
"""
def __init__(self, *pargs, **kwargs):
    for o in pargs:
        setattr(self, o.name, o)
    for k,v in kwargs.items():
        setattr(self, k, v)
```

**Comment by jlstevens** [comment]
@jbednar Interesting suggestion!

Pros:

1. Conceptually simpler
2. Would work with any parameterized object (even if the names aren't always nice)

Cons:

Doesn't help map ``keyword='val'`` to the tuple ``('keyword', 'val')``

For instance, in your example:

```python
Dimension(d.male_weight)
```

Is not supplying the name (``'male_weight'``) to the name parameter but supplies the label instead (``''Body weight of male participants''``). To define a name and label, you would have to do:


```python
Dimension('male_weight', label=d.male_weight) # OR
Dimension(('male_weight',d.male_weight))
```

Which isn't so helpful : now the alias is only used as a handle on the label string and you still have to repeat typing 'male_weight' twice.

Anyway, the idea of using ``*args`` instead of a list had occurred to me (and I think it is an improvement) and I hadn't realized this can be used for anything with a ``.name`` (making that part more general that I had initially thought).

To adapt your code, the more version (imho) is this:

```python
def __init__(self, *pargs, **kwargs):
    for o in pargs:
        setattr(self, o.name, o)
    for k,v in kwargs.items():
        setattr(self, k, (k,v))
```

Unfortunately, it is a little harder to explain in the docstring!

Here is another way you might try to generalize it though it isn't very sensible unless we can refine the idea some more:

```python
# Example 'mappers' where this could be a class parameter
mapper = lambda k,v: v                        # Same output as Jim's proposal above
mapper = lambda k,v: hv.Dimension(k, label=v) # Now v has to be a string to make a dim
mapper =  lambda k,v: (k,v)                   # Tuple usable for dims or sanitization

def __init__(self, *pargs, **kwargs):
    for o in pargs:
        setattr(self, o.name, o)
    for k,v in kwargs.items():
        setattr(self, k, self.mapper(k,v) )
```

I'm thinking it would behave like what you suggested but there is a way to specify a callable to output the appropriate value given the supplied keyword and value. One issue with this is that if you don't want to restrict the possible kwargs, these 'mapper's would have to be supplied at the class level (which might not be so bad really).

Hope that is clear! I still feel something like this is needed, but it does still need more thought...

**Comment by jbednar** [comment]
> For instance, in your example:
> Dimension(d.male_weight)

I don't see that code in my example, so I'm not sure what you mean. In any case, I'm not sure exactly why you want to map to a tuple instead of just the longer string, so please do explain that.

**Comment by philippjfr** [comment]
I'm closing this, it's been stale for over a year and both I and @jbednar agreed that we would like to see it closed.

**Pull request closed without merging**
