### PR TITLE
Add tick formatter plot options

### PR DESCRIPTION
**Pull request by philippjfr**
Adds plot options to control the axis formatting directly rather than using the `Dimension.value_format` which only accepts formatter functions. These accept:

* Format strings like '%d', '%.3f' etc.
* Python functions which are compiled to JS with flexx (or converted to a FuncFormatter in mpl)
* TickFormatter instances (or matplotlib.ticker.Formatter instances for mpl)

- [x] Add unit tests
- [x] Add documentation (to styling plots notebook)

### CODE REVIEW

**Comment by philippjfr** [comment]
@jlstevens Ready to review and merge once tests are passing.

**Comment by jlstevens** [comment]
Looks good! 

I feel that maybe we should have used bokeh's `PrintfTickFormatter` earlier but better late than never! I'll merge once the push build is green.

**Comment by philippjfr** [comment]
>I feel that maybe we should have used bokeh's PrintfTickFormatter earlier but better late than never! 

Definitely, I've never been able to give a good answer to questions about tick formatting.

**Comment by jlstevens** [comment]
Hmm, one thing...shouldn't matplotlib match the plot options here?

**Comment by philippjfr** [comment]
>Hmm, one thing...shouldn't matplotlib match the plot options here?

Aren't they?

**Pull request merged**
