### PR TITLE
Avoid dependence on NdElement and add deprecation warning

### PR DESCRIPTION
**Pull request by philippjfr**
Seemingly straightforward, needs further testing though.

Ended up reviving the NdElement deprecation PR here.

### CODE REVIEW

**Comment by jlstevens** [comment]
> Ended up reviving the NdElement deprecation PR here.

If you are trying to deprecate ``NdElement`` entirely, then I fully support that! The title of this PR will need to be updated though...

**Comment by philippjfr** [comment]
>If you are trying to deprecate NdElement entirely, then I fully support that! The title of this PR will need to be updated though...

That is the idea yes, the problem is pickle compatibility which would be a real pain.

**Comment by jlstevens** [comment]
> the problem is pickle compatibility which would be a real pain.

Agreed. For this reason if you do get pickle compatibility working, make sure to add a deprecation warning so that when the time comes, we can strip out the (inevitably!) horrible pickling hacks.

**Comment by philippjfr** [comment]
As outlined in https://github.com/ioam/holoviews/issues/1146, this PR now stops NdElement being used by default under any circumstances, with an additional deprecation warning issued when it an NdElement is instantiated for an unforeseen reason. In v2.0 NdElements will be removed and I'd even support dropping pickle support.

**Comment by jlstevens** [comment]
>  In v2.0 NdElements will be removed and I'd even support dropping pickle support.

Agreed. Version 2.0 is also there to allow us to clean up things like this and make a break with the 1.x series. We should consider backporting fixes from 2.0 into 1.7.x and if we find there is demand for continued 1.0 support, we should consider backporting key features from 2.0 into a 1.8 release (after 2.0).

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jlstevens** [comment]
The title should still be updated as I think it is now more general than what is suggested.

I assume I'm not seeing any ``__getstate__`` or ``__setstate__`` magic because the class is still there and if unpickled will warn? I'm not entirely sure that is true as I can't remember if pickle works via the constructor or not...

**Comment by jlstevens** [comment]
In discussion we decided that there would be plenty of warnings when working with ``NdElement`` (due to clone) even if the unpickling step itself doesn't warn.

Merging.

**Pull request merged**
