### PR TITLE
Fixes to setup.py for pip install

### PR DESCRIPTION
**Pull request by jlstevens**
PR to try and address #1734 and #1659.

### CODE REVIEW

**Comment by jlstevens** [comment]
Testing in a clean env using:

```
pip install https://github.com/ioam/holoviews/archive/setup_fixes.zip
```

Suggests that  #1734 is fixed (no more initial numpy error). I'm not yet sure what to do about #1659 though...

**Comment by jlstevens** [comment]
It looks like the issue with the ``examples`` function was the cause of the problems in #1659 as well. @philippjfr If you believe it is fixed now, I think it is ready to review/merge.

**Comment by philippjfr** [comment]
Thanks for fixing this, I know it was a pain.

**Comment by jlstevens** [comment]
I'm glad duplicating the ``example`` function was sufficient! I was expecting it to get a lot worse!

**Pull request merged**
