### PR TITLE
Fixed bokeh SideHistogram with (non)inverted axis

### PR DESCRIPTION
**Pull request by philippjfr**
When plotting an adjoint histogram in bokeh the dynamic color range functionality was not set up to handle an adjoint plot at the top.

screen shot 2018-01-30 at 10 27 32 pm

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks for this. I tested it out on a number of fairly complex examples and it does seem to be fixed. Happy to merge if you think this PR is ready.

**Comment by philippjfr** [comment]
Seems to need new test data:

```python
AssertionError: Display output mismatch: [{'values_changed': {"root['roots']['references'][27]['attributes']['code']": {'new_value': u"\n    color_mapper.low = cb_data['geometry']['y0'];\n    color_mapper.high = cb_data['geometry']['y1'];\n    source.change.emit()\n    main_source.change.emit()\n    ", 'old_value': u"\n    color_mapper.low = cb_data['geometry']['y0'];\n    color_mapper.high = cb_data['geometry']['y1'];\n    source.change.emit(undefined)\n    main_source.change.emit(undefined)\n    ", 'diff': u"--- \n+++ \n@@ -1,6 +1,6 @@\n \n     color_mapper.low = cb_data['geometry']['y0'];\n     color_mapper.high = cb_data['geometry']['y1'];\n-    source.change.emit(undefined)\n-    main_source.change.emit(undefined)\n+    source.change.emit()\n+    main_source.change.emit()\n     "}}}]
```

**Comment by philippjfr** [comment]
Hmm, I just got used to putting those ``undefined`` in because it's a TypeScript error, can remove them again and it should pass.

**Comment by jlstevens** [comment]
Tests are passing. Merging.

**Pull request merged**
