### PR TITLE
Added image hover examples to the docs

### PR DESCRIPTION
**Pull request by jlstevens**
In the bokeh element reference:

image

In the bokeh user guide:

image

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good, ready to merge?

**Comment by jlstevens** [comment]
> Looks good, ready to merge?

I think so.

**Comment by jlstevens** [comment]
Actually, the hover was set in the previous cell and was inherited in the screenshot above:

image

**Comment by philippjfr** [comment]
>Actually, the hover was set in the previous cell and was inherited in the screenshot above:

That seems fine, are you suggesting you want to make a change?

**Comment by jlstevens** [comment]
> That seems fine, are you suggesting you want to make a change?

No. I just realize that the screenshot I showed originally didn't show the updated magic that enabled the hover behavior shown.

**Pull request merged**
