### PR TITLE
Dashboard comms fixes

### PR DESCRIPTION
**Pull request by philippjfr**
A fix to get streams working on Jupyter dashboards and another fix to ensure events are processed when an error is received.

### CODE REVIEW

**Comment by jlstevens** [comment]
Great - though I assume we still need to use a dev version of ipywidgets for the dashboard comms to work?

**Comment by philippjfr** [comment]
>Great - though I assume we still need to use a dev version of ipywidgets for the dashboard comms to work?

Yes, I also remembered you have to satisfy the missing jQuery dependency. We'll be able to expose that in the ``notebook_extension`` though.

**Comment by jlstevens** [comment]
Thanks for clarifying. Ready to merge?

**Comment by philippjfr** [comment]
Yep

**Pull request merged**
