### PR TITLE
Deprioritized array interface

### PR DESCRIPTION
**Pull request by philippjfr**
Finally implements https://github.com/ioam/holoviews/issues/1236, this is long overdue since the ArrayInterface mostly just causes troubles due to mixed types. With this change you should only ever end up with an ArrayInterface when you pass in an ``NxM`` array explicitly.

### CODE REVIEW

**Comment by philippjfr** [comment]
Should be merged after https://github.com/ioam/holoviews/pull/2329. Should also reenable the Graph test that was disabled in that PR.

**Comment by jlstevens** [comment]
Agreed this is overdue. #2329 is now merged so those tests should be re-enabled and the tests seem to have failed right now. Maybe fixing that (or a rebase) will get the tests green so I can merge?

I'm a little worried that this change might cause problems as it affects so many things. But I also believe we really should do it now...

**Comment by philippjfr** [comment]
>I'm a little worried that this change might cause problems as it affects so many things. But I also believe we really should do it now...

It's revealing at least a few bugs caused by the ArrayInterface, which should be fixed by using the other interfaces. Tests also need updating because type comparisons are failing.

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jlstevens** [comment]
Looks good. I think this is important to do and hope it won't cause us any backwards compatibility headaches! Merging.

**Pull request merged**
