### PR TITLE
Add support for finalize_hooks to bokeh backend

### PR DESCRIPTION
**Pull request by philippjfr**
We've had ``finalize_hooks`` to apply customizations of plots that are currently not directly supported by holoviews in the matplotlib backend for a long time now. This PR adds support for ``finalize_hooks`` to bokeh as well.

Here is a simple example that can be used as a workaround for #1039:

```python
def apply_dt_formatter(plot, element):
    plot.handles['xaxis'].formatter = bokeh.models.DatetimeTickFormatter()

drange = pd.date_range(start="2014-01-01", end="2016-01-01")
vals = drange.values.astype('int64')/10**6
hv.Curve((vals, np.arange(len(vals))))(plot=dict(finalize_hooks=[apply_dt_formatter]))
```

bokeh_plot 28

### CODE REVIEW

**Comment by philippjfr** [comment]
hooks aren't called quite in the right place, will fix shortly.

**Comment by philippjfr** [comment]
Had to rebase to get the HeatMap changes. Ready to merge once it's passing.

**Comment by jlstevens** [comment]
Tests have passed. Merging.

**Comment by thoth291** [comment]
Doesn't work for my Linux installation (hv - 1.9.2).
image

**Comment by philippjfr** [comment]
Your call back references bokeh but you haven't imported it.

**Comment by philippjfr** [comment]
No worries, I know the feeling 😃

**Pull request merged**
