### PR TITLE
Adjoint overlay

### PR DESCRIPTION
**Pull request by philippjfr**
Implement overlaying of AdjointLayouts as originally outlined in https://github.com/ioam/holoviews/issues/987.

### CODE REVIEW

**Comment by jlstevens** [comment]
A screenshot/example would be good to illustrate the new behavior.

**Comment by jbednar** [comment]
Thanks!

**Comment by jlstevens** [comment]
Looks good - happy to merge once it is ready and the tests pass.

**Comment by philippjfr** [comment]
Travis has somehow decided not to run a PR build, or it's just being slow.

**Comment by philippjfr** [comment]
Looks like it's not going to, but there should be no failures in this PR and since the branch is up to date with master the push and PR builds are equivalent anyway. Merge away once it passes.

**Comment by philippjfr** [comment]
Appears to be an persisting py3 issue, so going to have to start another build anyway.

**Comment by philippjfr** [comment]
Ready.

**Pull request merged**
