### PR TITLE
Attempted fix of travis.yml

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by jlstevens** [comment]
What was that line supposed to do?

**Comment by philippjfr** [comment]
No idea, all I know is that it was failing.

**Comment by jbednar** [comment]
Presumably "| cat" can be added after the command if we want it not to
fail?  @ceball may remember why it was there.

**Comment by philippjfr** [comment]
> @ceball may remember why it was there.

As far as I know @ceball has never touched the .travis.yml in holoviews so I doubt he'd know.

**Comment by philippjfr** [comment]
It was added in https://github.com/ioam/holoviews/commit/798a0d71c658030969a13c5ca806e0638a8a4c4b almost 2 years ago, so I'm certain it's simply junk that stuck around.

**Pull request merged**
