### PR TITLE
Filter style keywords according to backend

### PR DESCRIPTION
**Pull request by jlstevens**
I think this functionality is best expressed with a screenshot:

screen shot 2016-07-27 at 2 54 03 pm

Note that ``linewidth`` applies to matplotlib and ``line_width`` applies to Bokeh.

### CODE REVIEW

**Comment by jlstevens** [comment]
In the last commit, I skip filtering if ``style_opts`` is an empty list.

The assumption is that things like ``OverlayPlot`` don't support styles (although they may support plot options). Applying filtering on ``OverlayPlot`` was part of why the tests failed.

Is this assumption reasonable?

**Comment by philippjfr** [comment]
>In the last commit, I skip filtering if style_opts is an empty list.

Sounds reasonable, yes. Not sure why not doing that would make it fail though.

**Comment by jlstevens** [comment]
Without it, I saw odd things in the Elements notebook...for instance the first overlay with errorbars ended up having red errorbars instead of the usual black ones.

**Comment by jlstevens** [comment]
Thanks for the last fix! Ready to merge once the tests pass.

**Comment by philippjfr** [comment]
Okay, tests passing at last. Merging.

**Comment by jbednar** [comment]
In the future, in cases where multiple backends use the same keyword to mean different things, should we support adding an identifier to specify the backend?  E.g. 'bokeh:linewidth=5" or "mpl:linewidth=10"?  This could also be used if we wanted to customize the two plots separately, e.g. to choose one color that looks good against mpl's default gray background, and a different color for Bokeh...

**Comment by jlstevens** [comment]
> E.g. 'bokeh:linewidth=5" or "mpl:linewidth=10"?

Seems like a good suggestion - please file an issue for this as a feature request.

**Comment by philippjfr** [comment]
That does sounds like a good suggestion, although I'd go for something like ``mpl:(linewidth=5 facecolor='red') bokeh:(line_width=5 fill_color='red')`` to separate them more cleanly.

**Pull request merged**
