### PR TITLE
Add Dimension.label replacing global alias state

### PR DESCRIPTION
**Pull request by philippjfr**
Addresses #1001 and supersedes #1075.

### CODE REVIEW

**Comment by philippjfr** [comment]
This is now passing without any major issues. This needs a lot more unit tests still and @jlstevens promised to write a short tutorial but we're both very happy with how this will work out.

**Comment by jbednar** [comment]
Looks good to me.  Some examples of usage would be good.

**Comment by philippjfr** [comment]
Yes, those should be part of the tutorial. I'd actually like to suggest to broaden the scope of that tutorial to discuss Dimensions in general, with a significant section devoted to ``name`` and ``label`` but also covering the ``redim`` method and the difference between ``range`` and ``soft_range``.

Another thing I've done in this PR is using ``strict`` dimension lookups in user facing APIs, which should result in much better tracebacks when referencing non-existing dimensions in many cases.

**Comment by jlstevens** [comment]
Thanks @philippjfr!

I'll shortly write up a notebook tutorial describing aliases, ``redim`` and the distinction between``range`` ``soft_range`` and add it to this PR.

**Comment by jlstevens** [comment]
I know have part of a Dimensions tutorial but I would like to work on #843 before continuing work on it. I am happy with this PR and would like to merge it now. Are you ok with me adding the Dimensions notebook to a different PR?

**Comment by philippjfr** [comment]
Sure, let's see how it goes. Better to get it in early to find issues.

**Pull request merged**
