### PR TITLE
Added various linked Stream examples

### PR DESCRIPTION
**Pull request by philippjfr**
A number of relatively simple linked stream examples with synthetic data. It might be nice to also have more complex examples which use real data. Feedback on structure of the examples welcome. Also worth considering whether I should add gifs to these notebooks so you can see what they're meant to do when viewed statically.

### CODE REVIEW

**Comment by jlstevens** [comment]
When I saw the commit message 'Added gifs for streams examples' I thought you added the gif files to the PR - which I would have objected to.

Links to GIFs are ok though. :-)

**Comment by jlstevens** [comment]
I've tried out all the examples and I like them!

``HeatMap_Tap`` has an issue with ``df`` being undefined and I think we still need to discuss exactly where these examples go. We need to figure out how to structure the elements gallery, these examples, what happens to contrib etc and also make sure it is a long term plan (i.e after the plotting backends have been split out, how we will support these examples with a live server eventually etc).

**Comment by jlstevens** [comment]
We decided on an organization here in issue #1379. That said, I would like to see that other material added to examples first at which point I would be happy to include these examples too.

**Comment by philippjfr** [comment]
Sounds good, there's still a few selection examples I wanted to add and we all agreed that this one was a good demo to show what datashader really does:

datashade_reveal

**Comment by jlstevens** [comment]
> HeatMap_Tap has an issue with df being undefined 

I ran through this notebook again and this still seems to be an issue..

**Comment by jlstevens** [comment]
I've rebased this PR and gone through the examples. They all work properly except for HeatMap_Tap which is missing the DataFrame ``df``. I believe we plan to add some real data to assets but I don't think that should be included just yet. Once the code is update, I'll add the compressed CSV file locally to test, at which point I'm happy to merge.

Maybe we should start adding asset files to a PR?

**Comment by jlstevens** [comment]
I've now updated the 'HeatMap Tap' example and I think I'm ready to merge. 

Here is the disease.csv.gz file we will want to add to ``examples/assets`` later: [disease.csv.gz](https://github.com/ioam/holoviews/files/1069297/disease.csv.gz)

**Pull request merged**
