### PR TITLE
Easy definition of sanitized substitutions

### PR DESCRIPTION
**Pull request by jlstevens**
This PR aims to address issue #264.

### CODE REVIEW

**Comment by jlstevens** [comment]
I think this PR is ready to merge. Here is an example of what it allows you to do:

```python
layout = (hv.Image(np.random.rand(10,10), 
         group=('Spectrum', 'Frequency spectrum'), 
         label=('Glucose', '$C_6H_{12}O_6$'))
+ hv.Image(np.random.rand(10,10), 
         group=('Spectrum', 'Frequency spectrum'), 
         label=('Water', '$H_2O$')))
```

Now you can select the two parts of the layout conveniently with ``layout.Spectrum.Glucose`` or ``layout.Spectrum.Water`` while showing the chemical compound names in the title (before you had to use some awkward, auto-generated sanitized string).

To make this less awkward, you can do this using the new ``Aliases`` helper function:

```python
al = hv.util.Aliases(Spectrum='Frequency spectrum', 
                     Water='$H_2O$', 
                     Glucose='$C_6H_{12}O_6$')

(hv.Image(np.random.rand(10,10), group=al.Spectrum,  label=al.Glucose)
+ hv.Image(np.random.rand(10,10), group=al.Spectrum, label=al.Water))
```

Lastly, the same principles apply setting dimension names using tuples:

```python
im =hv.Image(np.random.rand(10,10), 
             kdims=[('Lambda', '$\Lambda$'), ('Joules', 'Energy ($J$)')])
```

Which now makes methods such as select easier:

```python
im.select(Lambda=(-0.2, 0.2), Joules=(-0.3, 0.3))
```

Of course you can use the ``Aliases`` helper here too! 

After I add some tests, I *think* this is ready to merge and I definitely think it will help scientists (and anyone using LaTeX and special symbols really!) use HoloViews productively.

**Comment by jlstevens** [comment]
I've now added unit tests and one they pass, I think it is ready to merge (unless you have any comments!).

It is worth mentioning one limitation of this new system, the group/label/dimension name stays a string (the long string, not the short alias) which means your alias definitions won't be pickled together with the object. 

Aliases are defined as dictionaries (the ``aliases`` parameter) on the three global functions: ``hv.util.label_sanitizer``, ``hv.util.group_sanitizer``, ``hv.util.dimension_sanitizer``. Restoring your aliases comes down to restoring these dictionaries on these three objects appropriately.

**Comment by philippjfr** [comment]
Looks good, very happy to finally have a nice way to specify aliases. Since the tests are passing and I have no specific comments I'll go ahead and merge.

**Comment by jbednar** [comment]
Excellent!  Looks great.

**Pull request merged**
