### PR TITLE
Added initial_hook and renamed finalize_hook to final_hook

### PR DESCRIPTION
**Pull request by philippjfr**
This PR implements the suggestion made in #396 to add an ``initial_hook`` and rename ``finalize_hook`` to ``final_hook``.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good to me! 

Not much here to review and I assume this will be ready for an immediate merge...

**Comment by philippjfr** [comment]
Fixing some docstrings, ready once those are pushed. Hopefully the Options Tutorial won't complain.

**Comment by jbednar** [comment]
You can't just do self.finalize_hooks = self.final_hooks?

**Comment by philippjfr** [comment]
Could do but shouldn't we warn users that they should switch to ``self.final_hooks``?

**Comment by jbednar** [comment]
The original suggestion from Jean-Luc was "having an alias and eventually deprecating finalize_hooks", which I think is the right way to go about it.  I.e., immediately support the new way while making the old way continue to work, and then *later* deprecate the old way, in the following release.  Otherwise users have no time to update their code before they start seeing warnings, and thus they have to choose only a single HoloViews version for their code to support cleanly, which I think is unduly restrictive.

**Comment by philippjfr** [comment]
I just removed the deprecation warning, now only warning when finalize_hooks are being overridden by final_hooks.

**Comment by jlstevens** [comment]
Ok, tests are passing and looks ready to me. Merging.

**Pull request merged**
