### PR TITLE
Docs and minor code fixes

### PR DESCRIPTION
**Pull request by ea42gh**
struggled with git, hope I did not mess up too badly:
Minor documentation changes to improve readability.

### CODE REVIEW

**Comment by jlstevens** [comment]
@philippjfr Should be merge for 1.8.3?

**Comment by philippjfr** [comment]
Yes, let's merge it.

**Comment by ea42gh** [comment]
Since I am new to git, let me verify the steps I need to take:
* push the "Delete branch" button above, the branch will be deleted
  from ioam/holoviews.
* pull ioam/holoviews into my local master and do a rebase to delete the branch from my local copy
* push my local copy to my github copy of holoviews to delete the branch from my github repository??

Then, if I want to suggest further documentation changes, just start a new branch?

**Comment by philippjfr** [comment]
Pressing the "Delete Branch" button above should delete your branch, your branch isn't on ioam. All you should have to do is 1) press the button 2) switch to master locally then pull from ioam/holoviews and 3) delete your local branch with ``git branch -d docs_and_minor_code_fixes``. Now you're free to make a new branch based off master.

**Pull request merged**
