### PR TITLE
Histogram improvements

### PR DESCRIPTION
**Pull request by philippjfr**
Cleaned up and made various outstanding fixes for PR https://github.com/ioam/holoviews/pull/1784.

### CODE REVIEW

**Comment by philippjfr** [comment]
@jlstevens I've now got this passing. Do you still want a ``label_format`` parameter as you suggested in the original PR?

**Comment by jlstevens** [comment]
I still think the ``label_format`` idea is a good one, so it would be nice to include if it doesn't add too much additional work.

**Comment by philippjfr** [comment]
Not sure I like ``label_format`` for this, since it's the value dimension label but could be confused with the regular ``label``. Not sure I have much better suggestions though since I don't like ``vdim_label``.

**Comment by jlstevens** [comment]
So your issue is not with the idea, just the parameter name? How about``binned_format`` or ``aggregate_label`` or something like that?

**Comment by philippjfr** [comment]
``frequency_format`` is probably the most correct. Is that too long?

**Comment by jlstevens** [comment]
It is a bit long but I think it is ok. I'll try to think of something shorter but if I can't come up with anything, it will do.

**Comment by philippjfr** [comment]
Actually I probably prefer ``frequency_label``.

**Comment by philippjfr** [comment]
Tests are now passing (apart from a single transient), so I'll merge. @timothydmorton Thanks again for contributing, sorry this took so long to merge but it'll be in the next release.

**Pull request merged**
