### PR TITLE
Adding Topology in Condensed Matter MOOC as example

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by jlstevens** [comment]
Absolutely! Those notebooks are beautiful!

**Comment by jbednar** [comment]
Cool!

**Comment by jlstevens** [comment]
@basnijholt Anything else you want to add? I'm happy to merge right away.

**Comment by basnijholt** [comment]
For me it's good. Maybe @akhmerov has an opinion?

**Comment by akhmerov** [comment]
Nothing extra, all LGTM

**Comment by jlstevens** [comment]
Great! Merging.

**Pull request merged**
