### PR TITLE
Handle invert_axes for all Element types

### PR DESCRIPTION
**Pull request by philippjfr**
We never implemented ``invert_axes`` for all Element types. This code does that ensuring that any plot can now be adjoined.

Fixes: 

* https://github.com/ioam/holoviews/issues/1033
* https://github.com/ioam/holoviews/issues/780
* https://github.com/ioam/holoviews/issues/358

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good although I was hoping to see cruft removed with a replacement at the level of ``ElementPlot`` or some such base class.

Happy to merge once the tests pass, ideally with a few new unit tests.

**Comment by philippjfr** [comment]
This is not ready to review or merge.

**Comment by jlstevens** [comment]
> This is not ready to review or merge.

I know! Which is why I kept my comments general and checked you hadn't added the WIP tag (yet).

**Comment by philippjfr** [comment]
>Looks good although I was hoping to see cruft removed with a replacement at the level of ElementPlot or some such base class.

Not really possible, a baseclass can't know how to properly invert the data for a particular Element.

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jlstevens** [comment]
I'll merge though I do have one question.

> Not really possible, a baseclass can't know how to properly invert the data for a particular Element.

Perhaps this could be made easy at the data API level?

**Comment by philippjfr** [comment]
If it was just about ``invert_axes`` I'd definitely agree with you, but in many cases it's tied up with the code to ``invert_xaxis`` and ``invert_yaxis``, which definitely isn't a data API level concept.

**Pull request merged**
