### PR TITLE
Handle backend JS/CSS dependencies for static export better

### PR DESCRIPTION
**Pull request by philippjfr**
Automatically adds backend JS/CSS dependencies to ``static_html`` output and handles inlined bokeh dependencies if CDN is not available (e.g. for dev builds of bokeh).

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to review and merge.

**Comment by jbednar** [comment]
Sounds good!  

What does "CDN is not available" cover?  Does it just cover custom/dev builds where there are no corresponding files on CDN at all, or does it also handle transient unreachability of CDN?  I can't see what the mechanism is from the diff.

**Comment by jlstevens** [comment]
Looks good. My only worry is that``html_assets`` has the potential to get hairier and hairier over time but for now it is still ok.

Merging.

**Comment by philippjfr** [comment]
>What does "CDN is not available" cover? Does it just cover custom/dev builds where there are no corresponding files on CDN at all, or does it also handle transient unreachability of CDN (e.g. working offline)?

Only covers dev builds where there is no CDN version, in that case it just supplies the JS and CSS as raw text. However we could/(should?) also consider provide control over that.

**Pull request merged**
