### PR TITLE
Various fixes for handling coloring in plotting

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes some small bugs introduced in #1241 and reported as bugs in #1248.

### CODE REVIEW

**Comment by jlstevens** [comment]
Any way to add tests to make sure there isn't another regression?

**Comment by philippjfr** [comment]
Writing some right now.

**Comment by philippjfr** [comment]
Ready to merge whenever, tests passed and I only added a comment.

**Comment by jlstevens** [comment]
The pr build passed at least. Merging.

**Pull request merged**
