### PR TITLE
Dynamic inheritance in OptionTrees

### PR DESCRIPTION
**Pull request by jlstevens**
This PR is primarily to find out whether disabling ``merge_keywords`` has an effect on the test. If the tests continue to pass, then I propose keeping it disabled.

**Edit**: This PR turned into a fix for dynamic inheritance.

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks for that last fix! Hope the tests pass this time...

**Comment by jlstevens** [comment]
The existing tests passed and I am currently adding more unit tests. I should also mention that there is no need to change ``merge_keywords``and that this PR addresses issue #646.

**Comment by jlstevens** [comment]
I looked into the possibility of defining a utility to replace this code for generating a string specification:

```python
components = (obj.__class__.__name__,
                        group_sanitizer(obj.group),
                        label_sanitizer(obj.label))
 '.'.join([c for c in components if c])
```

But decided this pattern doesn't appear often enough in the codebase to bother with after grepping for ``'.'.join(``. For tuple specifications, there is already ``get_spec(obj)`` which seems sufficient as tuple specs are recommended anyway.

Having added unit tests to ensure the new dynamic inheritance keeps working, I think this PR is now ready for a review/merge.

**Comment by jlstevens** [comment]
I added one more unit test to simulate the %%opts magic. Ready to review/merge.

**Comment by jlstevens** [comment]
I just updated  the title of the PR as I confused myself thinking it is about options on ``DynamicMap``instead of dynamic inheritance!

**Comment by philippjfr** [comment]
Thanks for adding the tests. Very happy we finally fixed this.

**Pull request merged**
