### PR TITLE
Removed Collector and interface submodule

### PR DESCRIPTION
**Pull request by philippjfr**
We decided a while back that we'd move Collector elsewhere (probably topographica) and since the remaining files in ``interface`` are now gone, now would be a good opportunity to get rid of the entire ``interface`` submodule.

### CODE REVIEW

**Comment by jlstevens** [comment]
Happy to merge when the tests pass.

**Comment by philippjfr** [comment]
Okay, I've now moved it into featuremapper. Topographica was already importing it from there for some reason so it seemed easiest.

**Comment by philippjfr** [comment]
Only a 0.4% gain, still 81% coverage!

**Comment by philippjfr** [comment]
Going to merge, since you already agreed 😄

**Pull request merged**
