### PR TITLE
Made last set of positional arguments available in DynamicMap

### PR DESCRIPTION
**Pull request by jlstevens**
This PR is intended to address issue #705 

@philippjfr It is a simple change but it would be good if you could review it anyways.

### CODE REVIEW

**Comment by philippjfr** [comment]
Not sure I'm entirely happy with the name ``args``, it really doesn't tell me anything, ``last_args`` might be okay but really it's the last generated key, calling it args seems confusing. Maybe it would make sense to change the semantics of ``last`` and ``last_key`` on DynamicMaps to point to the most recently generated objects rather than the last one in the sorting order?

**Comment by jlstevens** [comment]
> Maybe it would make sense to change the semantics of last and last_key on DynamicMaps to point to the most recently generated objects rather than the last one in the sorting order?

I would prefer to keep ``DynamicMap`` as similar to ``HoloMap`` as possible. I'm happy to call it ``last_args`` if you prefer. 

The reason I think ``args`` is the correct name is that ``args`` and ``kwargs`` are the standard names when considering callables. Talking about 'keys' in this case seems like it would be confusing to me...

**Comment by philippjfr** [comment]
>The reason I think args is the correct name is that args and kwargs are the standard names when considering callables. Talking about 'keys' in this case seems like it would be confusing to me...

Don't really agree, our ``NdMapping`` based datastructures are about keys and adding another name for what is really just the last generated tuple key makes it seem like a separate concept when it really isn't. The DynamicMap is asked for a key and that key is passed as the args to the callback, so the args is a concept the callback worries about but at the DynamicMap level we should be talking about keys.

**Comment by jlstevens** [comment]
> ... at the DynamicMap level we should be talking about keys.

If you like, but I don't think should change the semantics of ``last`` or ``last_key``. Do you have another suggestion for a name?

**Comment by philippjfr** [comment]
>If you like, but I don't think we should change the semantics of last or last_key.

Yea, you're right, probably not a good idea. I'll think about it.

**Comment by jbednar** [comment]
`most_recent_key`?  `current_key`?

**Comment by jlstevens** [comment]
``last_executed_key``?

**Comment by jlstevens** [comment]
I think that streams make this a bit more complicated as there are now ``*args`` (anything in kdims, whether streams or not) or ``**kwargs`` which are streams not in the kdims. Only the *args part could be considered a key...

**Comment by philippjfr** [comment]
Should we close this? With addition of Callables this is probably quite out of date. I wouldn't mind if we made the last key and stream values available on the ``Callable`` though.

**Comment by jlstevens** [comment]
> I wouldn't mind if we made the last key and stream values available on the Callable though.

That would be reasonable and yes, I agree this original approach is now out-of-date. I don't think the Callable should know about keys versus streams but the arguments for the last call should be made available somehow.

**Comment by philippjfr** [comment]
Opened an issue for the suggestion and closing this PR as outdated.

**Pull request closed without merging**
