### PR TITLE
Update the bokeh reset ranges

### PR DESCRIPTION
**Pull request by philippjfr**
In https://github.com/bokeh/bokeh/pull/7948 I added ``reset_start`` and ``reset_end`` parameters for bokeh ranges to allow updating the range the reset tool resets to. This is a longstanding annoyance for HoloViews plots and this PR simply updates the reset_range whenever the actual ranges are updated.

- [x] Fixes https://github.com/ioam/holoviews/issues/2371

### CODE REVIEW

**Comment by jlstevens** [comment]
So in short, it no longer jumps the viewport about when using the reset tool?

**Comment by philippjfr** [comment]
Yes, it resets to the most recently applied range rather than the initially applied range.

**Comment by jlstevens** [comment]
I suppose my only question is...what if you explicitly want the original behavior? How do you disable it? And if you can disable it, we should document it...

**Comment by philippjfr** [comment]
>I suppose my only question is...what if you explicitly want the original behavior?

I don't think the original behavior was in any way desirable and consider it a bug. If you can think of an example where the original behavior is desirable I'd consider adding an option, but I really can't think of one.

**Comment by jlstevens** [comment]
> I don't think the original behavior was in any way desirable and consider it a bug.

I may have initialized the plot in some sensible reference frame that you may want to reset to. Anyway, I agree this is not the common case so I'll go ahead and merge.

**Pull request merged**
