### PR TITLE
Handle empty subplots and overlay layers

### PR DESCRIPTION
**Pull request by philippjfr**
This PR adds some additional validation to the plotting code to check for empty objects, which are then skipped rather than causing errors somewhere downstream in the code.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks like it might be ready? The tests are passing.

If you could add another unit test for this, that would be great but if it is too tricky to bother with then nevermind.

**Comment by philippjfr** [comment]
That last commit is a bit misnamed, bokeh now handles hv.Empty plots correctly and both backends treat empty objects as Empty except they also issue a warning.

**Comment by jbednar** [comment]
Glad to see Empty being handled more uniformly!  Just curious -- why is having an Empty generating a warning?  Isn't that a valid thing for someone to add to help get the layout they want?

**Comment by jlstevens** [comment]
Tests are passing. If you are happy with it, I am ready to merge.

**Comment by philippjfr** [comment]
Not yet no, further fixes coming.

**Comment by jlstevens** [comment]
> why is having an Empty generating a warning? Isn't that a valid thing for someone to add to help get the layout they want?

I was about the ask the same thing!

**Comment by philippjfr** [comment]
Sorry that was confusing and relied on the distinction between empty objects and Empty objects to parse. I just meant objects that have no length e.g. empty NdOverlays and HoloMaps will show a warning.

**Comment by jlstevens** [comment]
Ok. That is what I hoped you meant.

**Comment by philippjfr** [comment]
It turns out we weren't handling setting the visible flag on missing frames correctly, fixed that and am currently adding some unit tests.

**Comment by philippjfr** [comment]
When a HoloMap or DynamicMap key does not exist the corresponding glyphs are now hidden correctly. I also added some unit tests. Ready to merge once I've rebuilt the bokeh test data, which now includes the ``visible`` flag on the GlyphRenderer.

**Comment by philippjfr** [comment]
No eference data update needed apparently, just a py3 bug in one of my new unit tests. Ready to merge when tests pass.

**Comment by jlstevens** [comment]
Tests are green. Merging.

**Pull request merged**
