### PR TITLE
Replace (...) with .opts()

### PR DESCRIPTION
**Pull request by jordansamuels**
* Complements https://github.com/ioam/holoviews/pull/1759
* Execute `git grep -lE '\)\((style|plot|norm)=' -- examples | xargs  perl -pi -e 's/\)\((style|plot|norm)=/).opts($1=/g'`
* Spot check notebooks

### CODE REVIEW

**Comment by jlstevens** [comment]
@jordansamuels Your regex-fu is certainly better than mine!

I have now merged #1759 so you could rebase this PR off latest master? I can then try out this branch for some final checks. Alternatively, I can do the rebase if you give me the go-ahead because you have finished with your current set of changes.

**Comment by jordansamuels** [comment]
I found a few more, will update soon

**Comment by jordansamuels** [comment]
I picked up 1759 in this, so I'm not sure it'll go okay.  If not, I can make a separate PR.  I think this is because I pushed the branch then rebased rather than merged to update fork.

**Comment by jordansamuels** [comment]
Actually I'm going to close this and make a new one. Cleaner and doesn't pollute the history.

**Comment by jordansamuels** [comment]
Cleaner version is https://github.com/ioam/holoviews/pull/1763.

**Pull request closed without merging**
