### PR TITLE
Fix broken website links

### PR DESCRIPTION
**Pull request by jlstevens**
PR to address the broken links, many of which are listed in #1650

### CODE REVIEW

**Comment by jlstevens** [comment]
@ceball Any name is fine for the conda badge. What was it conflicting with though?

**Comment by ceball** [comment]
> Any name is fine for the conda badge. What was it conflicting with though?

I guessed it was the "conda" link in ``The recommended way to install HoloViews is using the conda command provided by Anaconda or Miniconda:`` but I didn't prove it.

**Comment by jlstevens** [comment]
Hmm. Thanks for fixing it, it worries me that rst has clashes like that...

**Comment by ceball** [comment]
I pushed my minor edits here, as requested. I hope nothing's controversial, but if anything is, let me know and I'll revert it.

**Comment by jlstevens** [comment]
Merging before 1.8.1. Happy for there to be a follow on PR for more fixes!

**Pull request merged**
