### PR TITLE
Collage for website and README

### PR DESCRIPTION
**Pull request by jlstevens**
Adding a collage of nice examples to the website and README.

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good!

**Comment by jlstevens** [comment]
Here is the preview when done from master (the preview from the PR doesn't spread across rows for some reason):

collage

**Comment by jlstevens** [comment]
This would be a good time to upload the logo so we can put it next to the *HoloViews* header (I suggest capitalizing it). Would also be good to update the entire README...

**Comment by jlstevens** [comment]
@philippjfr @jbednar Any idea how to get the logo on the same line as the heading in rst? I get this which is ugly:

image

using:

```
.. raw:: html

     <img src="http://assets.holoviews.org/logo/holoviews_color_icon_500x500.png" alt="HoloViews logo" height="70px" />

HoloViews
=========
```

It is possible with Markdown at least, see [nteract's README](https://github.com/nteract/nteract/blob/master/README.md).

**Comment by jbednar** [comment]
No idea.  Should the gallery include at least one plot showing a set of numerical sliders on a HoloMap (or DynamicMap)?  That's such a big selling point of HV that it's odd it's not included here.

**Comment by jlstevens** [comment]
> Should the gallery include at least one plot showing a set of numerical sliders on a HoloMap (or DynamicMap)

Do you think it has to be animated? Or would a static one with a slider get the point across?

**Comment by jbednar** [comment]
Either is probably fine.

**Comment by jlstevens** [comment]
In that case I suggest removing the linked stream example in the middle (bottom row) and replacing it with something that has a slider (and maybe some sort of linked stream).

**Comment by jlstevens** [comment]
Updated to show one with a slider:

collage

**Comment by jlstevens** [comment]
@philippjfr @jbednar Are we happy with this before I convert the README to markdown?

**Comment by philippjfr** [comment]
>@philippjfr @jbednar Are we happy with this before I convert the README to markdown?

Can we make the bottom row a tiny bit larger, basically scale them all up until their overall width right-aligns with the legend of the top row. Could even add a little bit of whitespace to the top row to give you more scope to scale up the bottom row.

**Comment by jlstevens** [comment]
All the examples in this collage are now examples in #1537. I would like to update some of the thumbnails which have changed and add links to where these examples will be before this PR is merged.

**Comment by jlstevens** [comment]
This PR will address #1596 once merged.

**Comment by jlstevens** [comment]
Every image in the collage now links to the page where that example can be found.

Note that the ``http://build.holoviews.org`` urls will need to be replaced with ``http://holoviews.org`` once the website is live. As we need to update the homepage with new content in a separate PR, this doesn't need to be changed now.

Here is what it looks like now:

image

@philippjfr Do you agree we should merge now then finish up the homepage?

**Comment by philippjfr** [comment]
Happy to merge this now, will still have to optimize file sizes for these but lets get it in place first.

**Comment by jlstevens** [comment]
The gifsicle utility seems to work well for gifs. Not sure what to do about pngs.

We should optimize these before the final homepage update.

**Comment by philippjfr** [comment]
I noticed the gifs were still fairly large even after you resized them, going to try a few other things.

**Comment by jlstevens** [comment]
I resized the gifs so their width was 500 pixels i.e they are still probably larger than they need to be.

**Comment by philippjfr** [comment]
Generally as long as they don't contain images the gifs compress very well so I'll try some compression tomorrow.

**Pull request merged**
