### PR TITLE
Tutorial and website fixes

### PR DESCRIPTION
**Pull request by philippjfr**
Minor fixes to the Tutorials before 1.4.2 release:

* Addresses issue #407 by removing Paths slicing examples.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good to me. It will need a test data update but once that is done and the tests are passing, I am happy to merge.

**Comment by philippjfr** [comment]
Will keep this open until everything else has been merged. Can review a website build just before release and make any final fixes here.

**Comment by jlstevens** [comment]
Good plan.

**Comment by jlstevens** [comment]
I'm running a link checker right now but I've already found one broken link - the link to the scipy paper. I'll note any others it finds...

**Comment by jlstevens** [comment]
Here are the broken links the checker found:

```
http://nipy.bic.berkeley.edu:5000/download/27 # SciPy paper
http://goo.gl/NH9FTB  # Also the SciPy paper
http://assets.holoviews.org/Tutorials/notebooks-1.4.1.zip
http://ipython.org/notebook/  # No trailing slash
```

It also says ``Status: 400 BAD REQUEST`` for this link although it works for me:

```
https://anaconda.org/anaconda/holoviews
```
That is the full list of problems with our links.

**Comment by philippjfr** [comment]
Ah the notebooks link is meant to be:

http://assets.holoviews.org/notebooks-1.4.1.zip

**Comment by jlstevens** [comment]
I've been told this is ready to merge and the changes look good.

**Pull request merged**
