### PR TITLE
Bokeh notebook tests

### PR DESCRIPTION
**Pull request by philippjfr**
Ready to merge now. Bokeh_Elements is now tested in Python2 at least.

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good to me.

**Comment by jlstevens** [comment]
Certainly better than no bokeh tests at all! What would it take to get the bokeh tests working with Python 3?

**Comment by philippjfr** [comment]
Getting it to sort predictably for comparison. I've not really figured out why that's so difficult.

**Comment by jlstevens** [comment]
Python 2's heterogenous sorting vs Python 3's homogenous only sorting?

**Pull request merged**
