### PR TITLE
Added CHANGELOG for 1.10.4

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by jlstevens** [comment]
Why would coverage decrease adding a changelog entry? It isn't code!

**Comment by philippjfr** [comment]
>Why would coverage decrease adding a changelog entry? It isn't code!

One of the tests failed with a transient, which triggered the coverage drop.

**Comment by jlstevens** [comment]
> One of the tests failed with a transient, which triggered the coverage drop.

I suppose I would prefer if coverage was only updated when the tests pass.

**Comment by jlstevens** [comment]
Anyway, all the tests are green now. Merging.

**Pull request merged**
