### PR TITLE
Added min_alpha parameter to shade and datashade

### LINKED ISSUE #2108: Datashader min_alpha not in Holoviews
Hi, I am new both at Holoviews and Datashader. But I tried to get the same plot that I get using datashader using Holoviews but it is being impossible because the datashade function does not have this min_alpha parameter that is present if I only use datashader function tf.shade.

It is important, since as I zoom in I get only a few bins really intense which mask almost the rest of the image.

Thank you

Code in datashader (part of if):
background = "black"
export = partial(export_image, export_path="export", background=background)
cm = partial(colormap_select, reverse=(background=="black"))

def create_image(x_range, y_range, w=plot_width, h=plot_height):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(data, 'X_coordinate', 'Y_coordinate', ds.count_cat("Gene"))
    img = tf.shade(agg, how = "eq_hist", min_alpha = 255)
    spread = tf.dynspread(img, threshold = 0.1, max_px = 1, how="over")
    return spread

p = base_plot(background_fill_color=background)
export(create_image(*data_smFISH_coords),"5_smFISH")
InteractiveImage(p, create_image)

Code using Holoviews ():
import numpy as np
import holoviews as hv
import datashader as ds
from holoviews.operation.datashader import aggregate, datashade, dynspread, shade

hv.notebook_extension('bokeh')
dynspread.max_px=1
dynspread.threshold=0.5
shade.cmap="#30a2da" # to match HV Bokeh default
data_smFISH = data
data_smFISH["Gene"] = data_smFISH["Gene"].astype("str")
dic_data = {i : hv.Points(data_smFISH[data_smFISH["Gene"].apply(lambda x: x == i)]
      [["X_coordinate", "Y_coordinate"]]) for i in data["Gene"].unique()}
Nd = hv.NdOverlay(dic_data, kdims=["Gene"])
agg = datashade(Nd, aggregator=ds.count_cat('Gene'))
dynspread(agg, how = "over")

### PR DESCRIPTION
**Pull request by jbednar**
Fixes #2108.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good to me!

**Comment by jbednar** [comment]
I can't find any error in the PR build; could it be a timeout?  It waited 53 minutes...

**Comment by philippjfr** [comment]
I've restarted that build about 5 times, don't know what the hell is going on.

**Comment by philippjfr** [comment]
It's not even the same error each time, going to merge.

**Pull request merged**
