### PR TITLE
Put .show method in user guide

### PR DESCRIPTION
**Pull request by Dr-Irv**
My small contribution to HoloViews.  Added documentation in user guide that mentions the matplotlib renderer `show` method, since it took me a LONG time to find it in documentation of an old pull request.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks, to start with could you clear the notebook, this will make it a lot easier to review and avoids cluttering the repo.

**Comment by Dr-Irv** [comment]
@philippjfr OK, I pushed the cleared notebook.

**Comment by philippjfr** [comment]
Seems reasonable, we should really add a bokeh renderer show method soon as well.

**Comment by philippjfr** [comment]
I stripped the notebook metadata as well. Looks good to merge now.

**Comment by jlstevens** [comment]
Looks fine to me too.

**Comment by philippjfr** [comment]
At some point we'll have to add a ``BokehRenderer.show`` and expose a top-level ``hv.show``, but I think there is already an issue about that.

**Comment by drs251** [comment]
#2481 😃 
More documentation is always a good thing, although this approach gave me some trouble once by cropping my plots (e.g. missing or incomplete color bars for images).

**Pull request merged**
