### PR TITLE
Add support for datetime axis on Image

### PR DESCRIPTION
**Pull request by philippjfr**
Adds support for datetime axes on Image, SheetCoordinateSystem, BoundingBox and Slice. The basics are all working including instantiation of an Image with datetime bounds and slicing and indexing. Will make it possible to generate datashaded images with datetime axes.

screen shot 2017-10-26 at 4 27 42 am

### CODE REVIEW

**Comment by jbednar** [comment]
Excellent!!!

**Comment by philippjfr** [comment]
Since this is the first modification to ``SheetCoordinateSystem`` and ``BoundingBox`` since it moved into HoloViews, one of @jbednar and @ceball can have the great honor of reviewing this PR.

**Comment by philippjfr** [comment]
While I think Image will correctly retain timezone information, I think datashade operations will discard them. I can't say I have a strong desire to tackle that issue right now.

**Comment by jbednar** [comment]
Since I got to it first, I will nominate @ceball. :-)

**Comment by philippjfr** [comment]
Needs lots of tests still of course.

**Comment by jbednar** [comment]
When this is done, maybe open an issue about the nanosecond precision issues and say that it's not something we expect to fix, but that if someone wants to use it for that purpose then here's what they would need to fix.

**Comment by philippjfr** [comment]
Okay, this is ready to review now. I've added a bunch of unit tests for the utilities and for the interfaces. Iris does not like datetime coordinates apparently so I've had to skip those tests.

**Comment by philippjfr** [comment]
This output:

```
HoloMap containing 28 items of type RGB
---------------------------------------

Key Dimensions: 
Date: Oct 25 2012 01:00 UTC...Nov 02 2012 16:00 UTC 
Layer Height (hPa): 850...1000 
Constant Dimensions: 
Frame: None...None 
Deep Dimensions: 
x: 0...400.0 
y: 0...350.0
R: 0...1 
G: 0...1 
B: 0...1 
```

changed to this:

```
HoloMap containing 28 items of type RGB
---------------------------------------

Key Dimensions: 
Date: Oct 25 2012 01:00 UTC...Nov 02 2012 16:00 UTC 
Layer Height (hPa): 850...1000 
Constant Dimensions: 
Frame: None...None 
Deep Dimensions: 
x: 0...400 
y: 0...350 
R: 0...1 
G: 0...1 
B: 0...1 
```

The latter is more correct so I've updated the test data but the push build isn't pulling it for some reason. It should still work so this can be merged after review.

**Comment by philippjfr** [comment]
I'm going to go ahead and merge this myself since other work depends on it and the best smoke test is likely using it a lot in action. @ceball promised he'd take a more in depth look even after merging.

**Pull request merged**
