### PR TITLE
Add Div Element

### PR DESCRIPTION
**Pull request by philippjfr**
As suggested in #2221 this PR adds a Div element wrapping around the bokeh Div model, which opens up all kinds of possibilities for nice demos.

- [x] Add plotting tests
- [x] Add element reference entry

### CODE REVIEW

**Comment by philippjfr** [comment]
Let's merge this now, we can add nice demos later.

**Comment by jlstevens** [comment]
Looks good to me. Merging.

**Comment by jlstevens** [comment]
Actually, are you planning to mention this in the user guide? Probably in the bokeh specific one?

**Comment by jlstevens** [comment]
Anyway, that can be a separate task and assigned an issue if necessary. Merging.

**Pull request merged**
