### PR TITLE
Doc updates jan18

### PR DESCRIPTION
**Pull request by ea42gh**
some minor changes to documentation.

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks for this! 

Skimming the diffs, your changes look good: just remember to strip out the metadata/kernel info from the notebooks when you are done.

**Comment by ea42gh** [comment]
Thought I had stripped it all out. What was left that could be stripped?
I'll see if I can adapt your strip_kernel.sh script!

**Comment by jlstevens** [comment]
There seems to be this stuff in the PR diff:

image

**Comment by ea42gh** [comment]
Weird: I don't see these on my side locally?!
I'll go check on github, but git claimed 'your branch is up to date'

**Comment by philippjfr** [comment]
Looks good, could you just make sure to clear the Gridded Datasets notebook as well. Then this is ready to merge I think.

**Comment by philippjfr** [comment]
Thanks again, all looks great now. I won't wait for tests since it's all text changes.

**Pull request merged**
