### PR TITLE
Ensured DynamicOperation uses the set of keys when converting HoloMap

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes issue raised in #882

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge when tests pass.

**Comment by jlstevens** [comment]
Are there any tests for DynamicOperation?

Otherwise, I'm happy to merge.

**Comment by philippjfr** [comment]
Yes there are a few.

**Comment by jlstevens** [comment]
Ok, there is one test failure but it is only a transient. Merging.

**Pull request merged**
