### PR TITLE
Added conda.recipe directory

### PR DESCRIPTION
**Pull request by jlstevens**
Finally add the ``conda.recipe`` directory. Not quite ready yet as I get:

```
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Undefined Jinja2 variables remain (['version']).  Please enable source downloading and try again.
```
This is something to do with the use of ``{% set sdata = load_setup_py_data() %}`` in the ``meta.yaml``. I'm not quite sure why though as the tested autover examples [also use this](https://github.com/ioam/autover/tree/master/examples/pkg_depend/conda.recipe) and it seems to work there. @ceball Any ideas?

### CODE REVIEW

**Comment by jlstevens** [comment]
Turns out I forgot to adjust the source path from ``.`` to ``..`

**Comment by jlstevens** [comment]
Seems to be working - I suppose I can add a README to match geoviews. The meta.yaml could be templated further but I don't think that belongs in this PR.

**Comment by jlstevens** [comment]
@philippjfr I think this is ready to review/merge when the tests pass.

**Comment by philippjfr** [comment]
Looks good.

**Pull request merged**
