### PR TITLE
Assign int index of coords if no coords in xarray object

### PR DESCRIPTION
**Pull request by jsignell**
I am not sure exactly how this should work if there is one set of coords specified but not another. But this is a start at least following on the ideas here: https://github.com/ioam/holoviews/pull/2579#issuecomment-417344368

### CODE REVIEW

**Comment by jsignell** [comment]
@philippjfr,  I think the failure is unrelated?

**Comment by philippjfr** [comment]
Looks like minor pyflakes issues:

```
tests/core/data/testxarrayinterface.py:281:9: F841 local variable 'expected_ys' is assigned to but never used
tests/core/data/testxarrayinterface.py:289:13: F841 local variable 'img' is assigned to but never used
```

**Comment by philippjfr** [comment]
The notebook test failure is indeed just transient though.

**Comment by philippjfr** [comment]
Thanks, I'll merge once tests are passing.

**Comment by philippjfr** [comment]
Very happy to have another contributor, thanks again!

**Pull request merged**
