### PR TITLE
Table finalize hook fix and example

### PR DESCRIPTION
**Pull request by jordansamuels**
One solution to https://github.com/ioam/holoviews/issues/1708

### CODE REVIEW

**Comment by jordansamuels** [comment]
(My additional commits were in confusion as I forgot it's another PR that's failing the Travis build.)

**Comment by jlstevens** [comment]
Thanks for this!

We started adding little feature examples just like this one in holoviews-contrib and we haven't yet found a new home for them (see [this example](https://github.com/ioam/holoviews-contrib/blob/master/notebooks/examples/arrow_plotting_hook.ipynb) which is very similar).

Discussing this with Philipp, we think this can be the first example in ``/examples/reference/features/bokeh``. Could you please initialize those directories and move your example there?

**Comment by jordansamuels** [comment]
@jlstevens yes, will reorganize and add the example soon.  Thanks.

**Comment by jlstevens** [comment]
@jordansamuels Thanks!

PR looks good merging.

**Pull request merged**
