### PR TITLE
Fix broken links in documentation

### PR DESCRIPTION
**Pull request by jlstevens**
This PR addresses issues  #198 and #1251 regarding broken links.

### CODE REVIEW

**Comment by jlstevens** [comment]
I'll run a website build and then run a link checker on dev.holoviews.org.

**Comment by philippjfr** [comment]
Would be good if you could update this paragraph in the index.rst with the most recent versions:

>HoloViews works with Python `2.7, 3.3, and 3.4 <https://travis-ci.org/ioam/holoviews>`_.
HoloViews is pure Python, but it also provides optional extensions
enabled with ``hv.notebook_extension()`` above that make it integrate
well with `Jupyter/IPython Notebook <http://ipython.org/notebook>`_ 2
and 3.

**Comment by jlstevens** [comment]
I rebased to get doc building working again. Making the suggested change now and then rebuilding the website.

**Comment by jlstevens** [comment]
Tests are now green and [build.holoviews.org](http://build.holoviews.org) has been rebuilt and all the links checked. I think this is ready to merge now.

**Comment by philippjfr** [comment]
Looks good.

**Pull request merged**
