### PR TITLE
Make the naming consistent

### PR DESCRIPTION
**Pull request by yuvallanger**
The other option is to rename everything in this tutorial into "waves" instead of "sine"

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks for doing this!

> The other option is to rename everything in this tutorial into "waves" instead of "sine"

What do you prefer? To be honest, I think ``waves`` might be a little nicer as the fact it is generated from a sine function is irrelevant. What matters is there is a pattern (of some sort) you want to look at.

**Comment by yuvallanger** [comment]
I myself would also go with `waves`, but there is already `sine_array` in
another tutorial file. Maybe also change it in the other tutorial?

**Comment by jlstevens** [comment]
Good point.

@philippjfr @jbednar What do you recommend?

**Comment by jbednar** [comment]
I prefer just `waves`.  Not sure if the tutorials need to be consistent with each other, but `waves` is probably better for both.

**Comment by philippjfr** [comment]
Sounds good to me.

**Comment by jlstevens** [comment]
@yuvallanger Are you planning to apply the same renaming to the other tutorial you mentioned?

If so great! Otherwise, I'm happy to merge as it is.

**Comment by yuvallanger** [comment]
Let's just merge it as it is. The other tutorial mentions sines and
cosines, so it isn't simply wavey things.

**Comment by jlstevens** [comment]
Ok great! And @yuvallanger thanks again for your PR!

**Pull request merged**
