### PR TITLE
Enabled matplotlib layout fix by default

### PR DESCRIPTION
**Pull request by philippjfr**
It's time to enable the matplotlib layout fix by default. There will be changes to the display data, so that will have to be updated, after careful review.

### CODE REVIEW

**Comment by jlstevens** [comment]
I agree...though how did you come up with the new vspace value? Trial and error?

**Comment by philippjfr** [comment]
>I agree...though how did you come up with the new vspace value? Trial and error?

Yeah, just like the previous value, it should behave more predictably now though. I'm not quite sure why the tests are still passing. Will have to review the test data.

**Comment by jlstevens** [comment]
The tests have now passed. Are the tests updated reviewed making this PR ready to merge?

**Comment by philippjfr** [comment]
No, for some reason the test data hasn't changed and I can't figure out why.

**Comment by jlstevens** [comment]
It might be worth thinking about how this links to #1041 before merging...

**Comment by jlstevens** [comment]
And yes, the fact the tests kept passing is weird!

**Comment by philippjfr** [comment]
I guess just merge it, can always revert it if something goes wrong.

**Comment by jlstevens** [comment]
Ok. Hope it works!

**Pull request merged**
