### PR TITLE
Apply matplotlib rc parameters correctly throughout

### PR DESCRIPTION
**Pull request by philippjfr**
I've long struggled with the correct way to apply rcparams in matplotlib, I now think a decorator which is applied during axis/figure creation, for all ``initialize_plot`` and ``update_frame`` calls and during rendering is the best approach.

Fixes https://github.com/ioam/holoviews/issues/1222

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready for review.

**Comment by jlstevens** [comment]
Seems like a sensible approach and I am happy with it as long as it works (preferably better than before).

My only comment is that I think ``mpl_context`` should be called ``mpl_rc_context`` to be explicit.

**Comment by jlstevens** [comment]
I suppose my only other comment is that it might be nice to test - if it is easy enough to set up such tests.

**Comment by philippjfr** [comment]
Ready now, pretty sure the coverage report is false, when I click through to it, it doesn't actually tell me which files now have reduced coverage.

**Comment by jlstevens** [comment]
> Ready now, pretty sure the coverage report is false

Yeah, a -1.4% coverage change is surprising.

Anyway, looks good and I'll now merge.

**Pull request merged**
