### PR TITLE
Fixed filtering of bokeh LineAnnotationPlot properties

### PR DESCRIPTION
**Pull request by philippjfr**
Minor self-explanatory fix.

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good, happy to merge once the tests pass.

**Comment by philippjfr** [comment]
Will have to add a dask 0.14 compatibility PR because they changed a bit of API, hopefully they can restore the correct behavior in 0.15.

**Comment by jbednar** [comment]
Have you filled an issue for dask pointing out the breaking change?

**Comment by philippjfr** [comment]
>Have you filled an issue for dask pointing out the breaking change?

Pinged the person responsibly after asking Matt about it. Temporarily pinned dask now. Once I've heard back we'll have to decide what to do.

**Comment by jlstevens** [comment]
> Temporarily pinned dask now

That means I can merge once the tests pass, right?

**Comment by philippjfr** [comment]
>That means I can merge once the tests pass, right?

Yes.

**Comment by jlstevens** [comment]
Great! 

The pr build has now passed and the push build will fail due to a transient. I don't see any reason to bother restarting the push build. Merging.

**Pull request merged**
