### PR TITLE
Update conda.recipe to noarch

### PR DESCRIPTION
**Pull request by jlstevens**
- [x] Updates the recipe to build noarch
- [x] Makes things more consistent with the recipe on conda-forge.
- [x] Removes conda-forge from extra channels (only used at build time)

### CODE REVIEW

**Comment by philippjfr** [comment]
Can't tell if the build.sh is now empty or whether you actually deleted it (which is what I'd expect). Otherwise this looks good to me.

**Comment by philippjfr** [comment]
Looks like it's deleted, GitHub should really highlight that somehow.

**Comment by jlstevens** [comment]
Odd. Github shows the deletion for me:

image

Anyway, the idea is that the last line there replaces the need for a script. As it is now noarch, there shouldn't be any worries about running across platforms (which I assume conda handles for you anyway).

**Comment by jbednar** [comment]
How does that screenshot show the difference between deleting the contents and deleting the file itself?  If it does, it's subtle...

**Comment by jlstevens** [comment]
I guess it doesn't make it clear that the whole file is removed. Anyway, ready to merge this PR?

**Comment by philippjfr** [comment]
Merging.

**Pull request merged**
