### PR TITLE
Fixed bugs in applying datashader operations

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes the dynspread operation which did nothing before and fixes a bug applying streams in the Dynamic utility when applying an dynamic operation to a static element.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jlstevens** [comment]
Looks good. 

My only suggestion is to maybe add a unit test for the condition fixed in ``Dynamic``?

**Comment by jlstevens** [comment]
Oh and there is a bit of trailing whitespace after the ``max_px`` definition. :-)

**Comment by jlstevens** [comment]
I'll merge when the tests go green.

**Comment by jbednar** [comment]
Looks good; thanks!  I'll update the Holoviews_Datashader tutorial once this is done, to add dynspread and timeseries operations (outliers).

**Comment by jlstevens** [comment]
Tests have now passed. Merging.

**Pull request merged**
