### PR TITLE
Minor fixes to Exporting tutorial, including example of PNG output

### PR DESCRIPTION
**Pull request by jbednar**
There were still some confusing and outdated bits.  The number of cells might have changed, which could change the output, but the rendered images should *not* have changed.

Provides further fixes for issue #468.

### CODE REVIEW

**Comment by jbednar** [comment]
Ready to merge, as far as I know.

**Comment by philippjfr** [comment]
Looks good, thanks for making it consistent!

**Comment by jlstevens** [comment]
Ok. This is a good chance to show how the website building system works.

@jbednar 
1. Click on 'Show all checks' next to 'All checks have passed'
2. Click on 'Details' next to s3-reference-data-cache (this name should be improved tbh).
3. Click on 'Update website' and follow it on buildbot.holoviews.org:8010. Once done, build.holoviews.org will be updated with the changes.

This is a lot easier than before though it could do with some improving (e.g names, more info on the webpage etc).

**Comment by philippjfr** [comment]
Okay, well since it's just text changes there's probably no need to rebuild the website in this case. I'll go ahead and merge.

**Comment by jlstevens** [comment]
Ok..nevermind. 

@jbednar It would be good if you could try to follow those instructions the next time you have a chance to update the website or notebooks...

**Comment by jbednar** [comment]
Ok.  So the idea is that these fixes will be seen the next time the website is changed by something else?

**Comment by jlstevens** [comment]
> Ok. So the idea is that these fixes will be seen the next time the website is changed by something else?

Correct. Either someone build the website for a PR and build.holoviews.org is updated or you wait till the nightly and the changes appear on dev.holoviews.org.

**Pull request merged**
