### PR TITLE
Layout.clone copies id and cols settings

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by jlstevens** [comment]
Makes sense. If this PR in response to a specific issue that was raised?

**Comment by philippjfr** [comment]
Yes two of them, it seems Overlays don't retain their id on relabel for some reason (as reported on Gitter) and @jbednar complained that the cols were being reset when using ``__call__``.

**Comment by philippjfr** [comment]
Not quite sure why there's no PR build on travis.

**Comment by jlstevens** [comment]
The tests are passing so I'll merge it now.

**Pull request merged**
