### PR TITLE
Avoid erroring when aggregating on non-numeric columns

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes https://github.com/ioam/holoviews/issues/2350
- [x] Adds unit test

### CODE REVIEW

**Comment by jlstevens** [comment]
I am fine with this PR as long as you have thought of the sort of aggregation you could imagine on non-numeric data, specifically the sorts of stats you could compute relating to counts.

**Comment by philippjfr** [comment]
That is a good point and I thought I'd have to add special handling for this but I just realized the current approach should work fine already. I'll just add an explicit unit test for this and then this can be merged.

**Comment by philippjfr** [comment]
Added unit tests to ensure non-numeric aggregations are allowed on string types.

**Comment by jlstevens** [comment]
Looks good. Merging.

**Pull request merged**
