### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by maxalbert**

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks a lot for going through the docs. It looks ready for merge but let me know if there's any other changes you're hoping to include in this PR.

**Comment by maxalbert** [comment]
I certainly expect that there will be more minor suggestions, typo fixes, etc., but I don't have any lying around right now, so I'll submit them gradually as I go along. I don't expect much to come before next week so I'm happy for you to merge this one.

**Comment by jlstevens** [comment]
Yes, thanks for going through the docs!

In addition to simple fixes (typos etc) we are happy to hear any suggestions for general improvements as we sometimes have trouble re-reading what we've written with a fresh eye. :-)

**Comment by maxalbert** [comment]
@jlstevens Yup, I almost certainly expect that I'll have suggestions for doc restructurings or additional documentation as well, but I think I need to get to better grips with HoloViews first.

**Comment by maxalbert** [comment]
Oh dear, looks like I've broken the build. Is this expected (because of subtle changes in the way the notebook is run), or did I actually break something? Please let me know where I should start looking to debug this and I'll try to take a look as soon as I can.

**Comment by philippjfr** [comment]
Not your fault, they were broken already. I'll get them working again in a bit, then it should merge cleanly.

**Comment by philippjfr** [comment]
Tests passed, merged.

**Comment by maxalbert** [comment]
Brilliant, thanks!

**Pull request merged**
