### PR TITLE
Fixed transposed expanded grid coords

### PR DESCRIPTION
**Pull request by philippjfr**
In investigating a bug in the ``Surface`` element I discovered that expanded coordinates are seemingly transposed from the expected orientation. Additionally the ImageInterface.coords method did not allow returning coordinate edges (rather than centers) like the other grid based interfaces.

If this PR passes there's clearly a gap in the unit tests, if it fails I'll have to investigate why this seemingly didn't cause issues or remove workarounds that were put in place elsewhere to make this work.

### CODE REVIEW

**Comment by philippjfr** [comment]
There were indeed quite a few tests checking for the wrong thing. I've now also updated the tests and added two new tests (which are executed against all grid interfaces) to act as a sanity check.

**Comment by philippjfr** [comment]
This is unlikely to have affected much user code since this is a fairly specialized API used mostly by the plotting code. It should however be included in the release notes.

**Comment by philippjfr** [comment]
Ready to merge once tests pass.

**Comment by philippjfr** [comment]
Although I suspect some plotting code may have to be updated.

**Comment by jlstevens** [comment]
Tests are green so I'll merge. Happy you can reason about when to transpose things because this sort of logic tends to melt my brain!

**Pull request merged**
