### PR TITLE
Hotfix v1.9.4

### PR DESCRIPTION
**Pull request by philippjfr**
Unfortunately a regression in the regrid operation was introduced in the hotfix 1.9.3 branch. This PR represents the fixes for that branch, and should not be merged.

Other PRs that would be good to get into this release are:

* https://github.com/ioam/holoviews/pull/2336
* https://github.com/ioam/holoviews/pull/2329

The latter would be good to ensure that we are actually testing against the latest versions of different libraries, which is what caused the ``regrid`` bug to slip through.

### CODE REVIEW

**Comment by philippjfr** [comment]
Once we get the flake fixes in #2340 merged this will be ready to release.

**Comment by philippjfr** [comment]
I've now cherry-picked the relevant flake fixes onto this branch. Should be ready to release now.

**Comment by jlstevens** [comment]
All the PRs mentioned are now merged. Maybe it is worth also getting #2346 in as that is bug fixes too?

**Comment by jbednar** [comment]
Several of the items in #2346 look like they are for Elements not present in 1.9.4, though...

**Comment by jlstevens** [comment]
That is a good point. If it is too much pain to cherry pick the commits that do apply to 1.9.4, then I suppose those fixes can simply be left out.

**Comment by philippjfr** [comment]
That's okay, I'll remove those while cherry-picking.

**Comment by philippjfr** [comment]
@jlstevens Now done, I think we can release this now.

**Comment by jlstevens** [comment]
The key tests we expect to pass (flakes, nosetests) are now passing on both Python 2 and 3. I'm now preparing the release.

**Pull request closed without merging**
