### PR TITLE
matplotlib2.0.0b4 compatibility fix (1/2)

### PR DESCRIPTION
**Pull request by stonebig**
#866

### CODE REVIEW

**Comment by jlstevens** [comment]
This PR looks like it might be redundant with #867 (which seems more complete as it isn't missing some of the necessary imports).

**Comment by stonebig** [comment]
it's not the same file. whith github interface, you modify on file at a time

**Comment by philippjfr** [comment]
Same as #867, tests failing due to anaconda pyqt issues. Going to merge and then fix the tests with #871.

**Comment by jlstevens** [comment]
> it's not the same file. whith github interface, you modify on file at a time

Ah, I see. Fairly awkward to have to build PRs that way! :-(

**Pull request merged**
