### PR TITLE
return correct data types after interp

### PR DESCRIPTION
**Pull request by rymurr**
step interpolation didn't work with a datetime x-axis. This small change fixes it

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks @rymurr, the contribution is greatly appreciated. This looks fine and I'll merge once tests pass.

**Comment by philippjfr** [comment]
Also congrats on your first contribution on GitHub!

**Comment by rymurr** [comment]
Haha thanks! About time I contribute too!

**Comment by philippjfr** [comment]
Thanks again, merging.

**Pull request merged**
