### PR TITLE
Fixed saving to html and json in Python 3

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/ioam/holoviews/issues/979 which ended up throwing bugs in ``Renderer.save`` in python3 when a string type was written to file. By defining the MIME type the encoding is applied correctly.

Needs some tests before merging.

### CODE REVIEW

**Comment by jlstevens** [comment]
Make sure to test this change with the archive functionality. If I remember right, there is code that needs to use the mime type to figure out how to encode the data (bytes vs strings).

**Comment by philippjfr** [comment]
>If I remember right, there is code that needs to use the mime type to figure out how to encode the data (bytes vs strings).

That's exactly the bit that was failing before I defined these. Will definitely test that.

**Comment by philippjfr** [comment]
Ready once tests pass.

**Comment by jlstevens** [comment]
Looks good. I'll merge now on the understanding that you did test this with ``hv.archive``.

**Pull request merged**
