### PR TITLE
Added support for scalars in dictionary interface

### PR DESCRIPTION
**Pull request by philippjfr**
As part of improving support for associating additional information with paths we decided that the dictionary interface should allow scalars as part of the format, avoiding having to duplicate the scalar value for each sample of a path/polygon. This PR makes this possible, while follow up PRs will start adding support for using this to represent scalar values associated with paths.

### CODE REVIEW

**Comment by jlstevens** [comment]
Glad to see this coming together!

I think we should work together on the documentation to make sure we convey how all these different threads come together (multi-interface, associated user API that still needs fleshing out, support for constant columns added in this PR). In theory, there could also be plotting code changes e.g supporting changing color along a path but that is less critical.

**Comment by philippjfr** [comment]
There will be a path/polygon/geometry user guide to go alongside the gridded and columnar ones.  Once this PR is merged I can start working on that while I actually start implementing support for plotting scalar and continuously varying variables associated with paths. The user API, which I expect to be fairly minimal additions on top of what we currently have, can follow shortly after that. So the steps from here are:

1) Expand Path/Polygon key dimensions to allow additional scalar variables and add validation to ensure that these variables are indeed scalar.
2) Extend Path/Contour and Polygons plot implementations to support scalar and continuous variables and color the glyph/artists accordingly.
3) Start writing a path/geometry user guide to demonstrate how to construct and work with path data.
4) Decide on and implement any additional user level API necessary for easily working with paths.

**Comment by philippjfr** [comment]
Anyway, this PR is ready to merge once tests pass.

**Comment by jlstevens** [comment]
For your step 2) don't we also want the ``op``/``norm`` system in place first?

**Comment by philippjfr** [comment]
>For your step 2) don't we also want the op/norm system in place first?

Not really, colormapping is never really going to fit into that since that's done client-side.

**Comment by jlstevens** [comment]
I think there are possibilities other than just colormapping - for instance, mapping a vdim to the thickness along the path. Not about how technically feasible that might be but it does fit in conceptually with the improved vdim support for path types.

**Comment by philippjfr** [comment]
>for instance, mapping a vdim to the thickness along the path.

Oh absolutely! There's a bunch of possibilities from line widths to alphas and other things I can't imagine right now, but that can happen independently from the path stuff I described above.

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by philippjfr** [comment]
I think another optional improvement for the dictionary interface will be to allow combining multiple dimensions, letting you do something like this:

```python
{('x', 'y'): np.random.rand(10, 2), 'z': 1}
```

Might be a more natural way to represent paths.

**Comment by jlstevens** [comment]
> ... letting you do something like this:

{('x', 'y'): np.random.rand(10, 2), 'z': 1}

I think we might have discussed something similar in the past (related, if not exactly the same). It seems like a reasonable thing to support at some point.

Anyway, tests have passed and I'll merge now.

**Comment by philippjfr** [comment]
I think we discussed in context of the grid interfaces for the value dimensions, for example for RGBs.

**Pull request merged**
