### PR TITLE
Fixed group and label assignment bug in Element_Operation.__call__

### PR DESCRIPTION
**Pull request by drs251**
Reopen of PR #1110, to address issue #1106. @philippjfr Perhaps it will work this time, if not just go ahead and make your own PR - I really need more practice with git...

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks so much for going through the effort, practice makes perfect. I'm sure it'll work this time.

**Comment by philippjfr** [comment]
Okay our test build issues persist but now it's on me to figure out a solution.

**Comment by philippjfr** [comment]
Tests passed at last. Thanks again and congrats on your first PR!

**Comment by drs251** [comment]
Awesome, thank you!

**Pull request merged**
