### PR TITLE
Made datetime handling in plotting code more general

### PR DESCRIPTION
**Pull request by philippjfr**
Improves datetime handling for ``datetime.datetime`` and ``pd.tslib.Timestamp`` types. Needs a bunch of unit tests.

### CODE REVIEW

**Comment by philippjfr** [comment]
Very happy with this refactor the code is no longer duplicated and now handles datetime types more consistently. Also added a bunch of unit tests just now. Ready to merge when tests pass.

**Comment by jlstevens** [comment]
Ok, the tests have now passed. The changes look good and I am very happy to see the code simplified and the addition of new tests.

Merging.

**Comment by stonebig** [comment]
hi small remark. testing with holoviews latest build, I get this error:
`````
# Holoviews 
# for more example, see http://holoviews.org/Tutorials/index.html
import holoviews as hv
%load_ext holoviews.ipython
fractal = hv.Image(image)

((fractal * hv.HLine(y=0.16)).hist() + fractal.sample(y=0.16))
``````

````
C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\holoviews\core\util.py:26: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  datetime_types = datetime_types + (pd.tslib.Timestamp,)
````

**Comment by philippjfr** [comment]
Thanks for the note, I'll make a PR with the fix now.

**Comment by stonebig** [comment]
further down, i see errors in statsmodels "The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools"... maybe a full check would be nice

**Comment by philippjfr** [comment]
>further down, i see errors in statsmodels "The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
from pandas.core import datetools"... maybe a full check would be nice

Could this be triggered by some other dependency? I think it's probably seaborn, because holoviews does not import statsmodels directly.

**Comment by stonebig** [comment]
it's not triggered by holloviews, just meant that there may be a lot more deprecation warnings to chaze per holoviews  with pandas-0.20.0rc1

**Comment by philippjfr** [comment]
I see, yes that makes sense, I'll try it out.

**Comment by stonebig** [comment]
oups ! it's a new kind of deprecation for me "FutureWarning". I new "DeprecationWarning" and "UserWarning" up to now.

**Pull request merged**
