### PR TITLE
Interrupting a Collector now returns all available data

### PR DESCRIPTION
**Pull request by jlstevens**
Title says it all: ``KeyboardInterrupt`` no longer loses the available data. Shame I didn't implement this before I actually needed it!

Addresses #658

### CODE REVIEW

**Comment by jlstevens** [comment]
I will note that the last commit uncomments a line ``interval_hook(0)`` which is something I think is a bit of a mistake. The problem is that I can't remember if it is really needed or just something we added to get progress bars working...

Without this line commented, the ``advance_time`` hook alternates between actually advancing time with pointless time advances of zero in between. This is bad when you have side effects such as printing (as in the tutorial).

**Comment by philippjfr** [comment]
Looks fine, going to restart the push build and then merge.

**Comment by jlstevens** [comment]
Ok all the tests have passed now. Ready to merge.

**Comment by jlstevens** [comment]
Though maybe we should discuss the line ``interval_hook(0)``? I think it shouldn't be there but maybe that is an issue for a different PR?

**Comment by philippjfr** [comment]
>I think it shouldn't be there but maybe that is an issue for a different PR?

Yes sounds like a separate PR issue, perhaps either reverting my changes or completely rehauling the progress bar.

**Comment by philippjfr** [comment]
Merging.

**Pull request merged**
