### PR TITLE
Improve comm message handling

### PR DESCRIPTION
**Pull request by philippjfr**
This PR makes a number of improvements to comm message handling. To summarize:

* Avoids bokeh registering a comm handler avoiding bokeh raising warnings outside a notebook environment
* Reuses the ``bokeh_msg_handler`` from pyviz_comms avoiding code deduplication
* Updates the widget based message handler to support changes made in https://github.com/pyviz/pyviz_comms/pull/26

### CODE REVIEW

**Comment by philippjfr** [comment]
Let's merge this at the same time as https://github.com/ioam/holoviews/pull/3156

**Comment by philippjfr** [comment]
Should also bump the required pyviz_comms version in one of these PRs.

**Comment by jlstevens** [comment]
Looks good (happy to see code move out to `pyviz_comms`) and happy to merge when you tell me to i.e to coordinate with #3156 although that PR doesn't seem ready yet at the tests are currently failing.

**Comment by philippjfr** [comment]
>happy to merge when you tell me to i.e to coordinate with #3156 although that PR doesn't seem ready yet at the tests are currently failing.

The PR is ready it's simply waiting on a pyviz_comms release to happen.

**Comment by jlstevens** [comment]
In that case I'll merge. Thanks!

**Pull request merged**
