### PR TITLE
Fixed bug inverting matplotlib heatmap

### PR DESCRIPTION
**Pull request by philippjfr**
Matplotlib handles inverting the data automatically if an axis is inverted which means that the code to invert the HeatMap data was actually undoing the inversion.

- [x] Fixed https://github.com/ioam/holoviews/issues/2633

### CODE REVIEW

**Comment by jbednar** [comment]
Good catch.  Do you know if mpl has *always* done that, or if it's a change in some more recent version?

**Comment by philippjfr** [comment]
>Do you know if mpl has always done that

I think it's always done that, no other plot classes implement this inversion, so I think it was accidentally adding while I added support for it in the bokeh backend.

**Comment by jlstevens** [comment]
Glad this is fixed although I worry about how many people might have been affected by this without realizing it.

**Comment by jlstevens** [comment]
Looks good. I'll merge when the tests pass.

**Pull request merged**
