### PR TITLE
Updates to setup.py and meta.yaml

### PR DESCRIPTION
**Pull request by jlstevens**
This PR updates setup.py and meta.yaml for the 1.7 release. After release, setup.py will be updated to use #1368.

### CODE REVIEW

**Comment by jlstevens** [comment]
Seems that the ``extra_requires`` didn't like ``'bokeh=0.12.5'``.

**Comment by philippjfr** [comment]
>Seems that the extra_requires didn't like 'bokeh=0.12.5'.

Doesn't it need to be 'bokeh==0.12.5' for setuptools?

**Comment by jlstevens** [comment]
> Doesn't it need to be 'bokeh==0.12.5' for setuptools

I'll try that. Wasn't sure of the syntax and assumed it matched conda.

**Comment by philippjfr** [comment]
Looks good, let's release!

**Comment by stonebig** [comment]
hi Holoviews developpers. IS it still relevant to have that Pinned bokeh-0.12.5 in 0.18dev2 ?

**Comment by jlstevens** [comment]
The next dev release will pin to 0.12.6 which has now been released. You should be able to use that.

**Pull request merged**
