### PR TITLE
Fixes for datashader reduction error

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes bug in datashade/rasterize operation error handling
- [x] Defines missing 'sum': rd.sum reduction

### CODE REVIEW

**Comment by jbednar** [comment]
Whoa; how did that ever work before?  Needs a new test?

**Comment by philippjfr** [comment]
What do you mean? This was not a critical error, the error message was slightly wrong, and you could not declare the sum reduction as a string, that's about it.

**Comment by philippjfr** [comment]
Ready to merge.

**Comment by jbednar** [comment]
Ah, I didn't see that it was only in an error message; that's why it didn't matter much before.

**Pull request merged**
