### PR TITLE
Ensure Plots correctly cache lookups in DynamicMaps

### PR DESCRIPTION
**Pull request by philippjfr**
Ensures the plots respect the _force option telling them not to request a new frame on the DynamicMap, both during initialization and for subsequent updates. Relies on the fact that the initialization pass of creating Plots does not care which exact Element is being plotted, since it is subsequently updated again anyway.

### CODE REVIEW

**Comment by philippjfr** [comment]
I'm really happy to have finally simplified this logic, I thoroughly hated ``get_dynamic_item`` and I've not replaced it completely. We now also explicitly throw an exception when trying to display a composite plot containing multiple HoloMaps with non-overlapping dimensions. Another happy side effect is that DynamicMaps with non-overlapping dimensions now work:

nonoverlap

**Comment by jlstevens** [comment]
Looks great and I am also really happy to see this simplified.

The tests have passed now. Merge?

**Comment by philippjfr** [comment]
Yes, ready now.

**Comment by jlstevens** [comment]
The push builds have passed and the failures in the pr builds are just transient display test errors. Merging.

**Pull request merged**
