### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by maxalbert**

### CODE REVIEW

**Comment by philippjfr** [comment]
All good fixes thanks! Let us know when you're done. The tests won't pass because some notebook output has changed but I can handle that after merge.

**Comment by maxalbert** [comment]
Feel free to merge now, I don't have anything on my list at the moment. (I tend to only submit PRs when I don't expect any immediate further changes.)

**Comment by maxalbert** [comment]
I submitted a couple of PRs to the `holoviews-data` repository which fix the same typos in the reference data. I'm not entirely sure how the whole build/testing process works but I hope this should fix the failing build.

**Comment by philippjfr** [comment]
I'll go ahead merge, will fix the notebook tests myself.

**Pull request merged**
