### PR TITLE
Fixed inconsistent whitespace that was messing up hv.help()

### LINKED ISSUE #2710: Misformatted help text
If I do `hv.help(hv.Labels)`, I  get bogus formatting for some of the parameters:

```
>>> hv.help(hv.Labels)
Parameter docstrings:
=====================

cdims:    The constant dimensions defined as a dictionary of Dimension:value
          pairs providing additional dimension information about the object.
          
          Aliased with constant_dimensions.
datatype: A priority list of the data types to be used for storage
                 on the .data attribute. If the input supplied to the element
                 constructor cannot be put into the requested format, the next
                 format listed will be used until a suitable format is found (or
                 the data fails to be understood).
extents:  Allows overriding the extents
                        of the Element in 2D space defined as four-tuple
                        defining the (left, bottom, right and top) edges.
kdims:    The label of the x- and y-dimension of the Labels element in form
          of a string or dimension object.
```

It looks like this happens when the docstring includes different spacing on the first line than on subsequent lines, as for `datatype` and `extents` below.  It would presumably be a lot of work to go through all Parameterized objects and make sure they have the same spacing on every line, so instead could we put some sort of preprocessing code into hv.help to normalize the whitespace before calling pydoc.help()?          

```
class Labels(Dataset, Element2D):
    kdims = param.List(default=[Dimension('x'), Dimension('y')],
                       bounds=(2, 2), constant=True, doc="""
        The label of the x- and y-dimension of the Labels element in form
        of a string or dimension object.""")
```

    cdims = param.Dict(default=OrderedDict(), doc="""
       The constant dimensions defined as a dictionary of Dimension:value
       pairs providing additional dimension information about the object.

       Aliased with constant_dimensions.""")

```
class Dataset(Element):
    datatype = param.List(datatypes,
        doc=""" A priority list of the data types to be used for storage
        on the .data attribute. If the input supplied to the element
        constructor cannot be put into the requested format, the next
        format listed will be used until a suitable format is found (or
        the data fails to be understood).""")
```

```
class Element2D(Element):

    extents = param.Tuple(default=(None, None, None, None),
                          doc="""Allows overriding the extents
              of the Element in 2D space defined as four-tuple
              defining the (left, bottom, right and top) edges.""")
```

### PR DESCRIPTION
**Pull request by jbednar**
Fixes #2710. I had thought that there would be lots of misformatted docstrings, but it turned out there were only a dozen or so, so I went ahead and fixed those.  Also made trivial changes to docs where I spotted issues. Ready to merge when tests pass.

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks for doing this!

**Comment by jbednar** [comment]
@jlstevens, it looks like the failing tests are testing the output of help in these cases (at least in my spot checks).  Can you please check that and if so update the test data, as this change intentionally improves the help output?

**Comment by jlstevens** [comment]
@jbednar I've checked and the failures are in the options notebook which is where I would expect such a breakage. I'm updating the test data now.

**Comment by jlstevens** [comment]
The pr build is now green. Merging.

**Pull request merged**
