### PR TITLE
Fixes for bound_range utility

### PR DESCRIPTION
**Pull request by philippjfr**
Since the introduction of ``ndloc`` the precise numerical precision of Image coordinates is not a real issue anymore. This PR drops the rounding that we previously applied to the density based on the system float precision. This means that Image can handle very small values, which are currently rounded to zero. I've also filtered some warnings.

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks like there's a test failure here:

>AssertionError: 2.9999999999999996 != 3

Suppose this is expected but we need to decide whether nicely rounded density values are more important than handling very small value ranges, which a user reported issues with.

**Comment by jlstevens** [comment]
> Suppose this is expected but we need to decide whether nicely rounded density values are more important than handling very small value ranges, which a user reported issues with.

Any way to detect tiny ranges in which case rounding should be disabled?

**Comment by jlstevens** [comment]
Fix makes sense to me: if after rounding you get zero, use the full precision. if this works correctly, I am happy to merge.

**Comment by philippjfr** [comment]
Great, ready to merge then.

**Pull request merged**
