### PR TITLE
Add options inheritance on OverlayPlot

### PR DESCRIPTION
**Pull request by philippjfr**
Initial attempt at addressing https://github.com/ioam/holoviews/issues/638, total WIP to see how tests are affected, but it may really be this simple.

### CODE REVIEW

**Comment by jlstevens** [comment]
Given the tests pass, I think it might be something to enable for 1.7. It is something that we've wanted for a long time and as long as we give the option to restore the old behavior, this might be an easier win than we anticipated!

**Comment by philippjfr** [comment]
Yes, I'm really pleasantly surprised by this, it behaves exactly like I'd expect and after running through a bunch of notebooks my observations are twofold:

* All the notebooks I've run through with this change have not exhibited any change in behavior.
* Almost every notebook I've run through has at least one case where this change would let you simplify the options specification.

However my bandwidth is also limited, so I'd suggest we get as many people playing around with this as possible. As a start, @jlstevens, @jbednar could you both take this PR for a spin on as many notebooks as you can?

**Comment by philippjfr** [comment]
Here's an illustrative example:

```python
%%opts Overlay [xticks=10] Curve [xticks=2 width=600 height=400] Points [show_grid=False bgcolor='WhiteSmoke']
hv.Curve(range(10)) * hv.Curve(np.random.rand(10)) * hv.Points(np.random.rand(100,2)*9)
```

The effective applied options for this example are: ``{'xticks': 10, 'width': 600, 'bgcolor': 'WhiteSmoke', 'show_grid': False, 'height': 400}``

bokeh_plot 30

**Comment by jlstevens** [comment]
It is a fairly small PR so it should be easy to revert if we suddenly find major issues (which seems doubtful). 

For this reason, I think the best way to get it well tested is simply to merge it ASAP. It might still be worth adding a class attribute toggle first though...

**Comment by jlstevens** [comment]
The tests have passed so I will merge now. I'm hopeful this will address one of the biggest annoyances without causing much trouble!

**Comment by jbednar** [comment]
Fabulous!  I think that this will go a long way towards making it intuitive to set and use options.

**Pull request merged**
