### PR TITLE
Fixed a bug where the group and label of a Holomap would get messed u…

### PR DESCRIPTION
**Pull request by drs251**
…p by ElementOperation.__call__ - #1106

### CODE REVIEW

**Comment by drs251** [comment]
Hope I didn't screw this up too badly, it's my first PR ever... 😊

**Comment by jlstevens** [comment]
Looks good, thanks!

I'm just trying to remember the original reasoning we had for copying the group/label across...

**Comment by drs251** [comment]
Manual copying seems to be unnecessary, as this is done by `clone()` - I've tested it.

**Comment by philippjfr** [comment]
I think this is correct, it doesn't make sense for a ``HoloMap`` to inherit the ``group`` and ``label`` of the input since it already computes a new group and label from the processed Elements. I expect there to be a lot of test failures, so we'll have to update the test data.

**Comment by philippjfr** [comment]
Only one small failure in ``Showcase``, where ``contours``, ``threshold`` and ``gradient`` operations are used. No change in display data though. Rebuilding tests now.

**Comment by philippjfr** [comment]
@jlstevens Seems the PR build here failed uploading the test data:

```
 aws s3 cp --recursive --region eu-west-1 ./doc/test_html "s3://travis.holoviews.org/build_$TRAVIS_BUILD_NUMBER"
upload failed: doc/test_html/holoviews_Continuous_Coordinates_py2.html to s3://travis.holoviews.org/build_6556/holoviews_Continuous_Coordinates_py2.html Unable to locate credentials
```

any ideas?

**Comment by jlstevens** [comment]
Hmm, I'm guessing it is [this line](https://github.com/ioam/holoviews/blob/master/.travis.yml#L13)

I have vague memories of the AWS key being encrypted as an environment variable. I assume there is a credentials issue for some unknown reason...

**Comment by philippjfr** [comment]
@drs251 Sorry about holding this up but we uncovered an issue in our testing infrastructure which I've only just fixed. Do you mind merging or rebasing this PR against current master, then I'll be able to merge it.

**Comment by drs251** [comment]
@philippjfr I've managed to update personal fork and merge the PR there, but I can't figure out how to modify this PR to the main repo - or should I make a completely new PR? (Sorry, GitHub is kind of new to me...)

**Comment by drs251** [comment]
@philippjfr Never mind, I think i figured it out, but the test is still failing for some reason... 😦

**Comment by philippjfr** [comment]
@drs251 Perfect thanks! The test failure is expected, we test the output of all our tutorial notebooks and one of them has changed slightly with this PR. I'm about to rebuild the test data and  then merge.

**Comment by philippjfr** [comment]
Sorry again, it seems your merges weren't quite right. Perhaps the easiest thing would be to reopen the PR starting with current master. Alternatively I'd be happy to resubmit the PR myself, you'd still be the commit author, but I don't want to steal the glory of your first merged PR.

**Pull request closed without merging**
