### PR TITLE
Parser fixes

### PR DESCRIPTION
**Pull request by philippjfr**
Two small fixes for the parser, the first fixes passing dictionary literals by eliminating duplicate commas generated by the parser, fixing part of the issue described in #270, e.g. this is now allowed:

```python
%%opts Scatter [fontsize={'title': '20pt'}]
hv.Scatter(np.random.rand(100,2), group='A')
```

Secondly it fixes a bug when a opts definition includes nested bracketing as described in #930, which described an issue where:

```
%%opts Curve (color=hv.Cycle(values=sns.color_palette('Set1')))
hv.Overlay([hv.Curve(np.arange(10)*i) for i in range(3)])
```

Was not evaluated correctly. This is now also correctly processed.

Note that this does not fix all issues mentioned in #270, e.g. ``aspect=dict(x=1, x=2, z=3)`` still fails to evaluate, but it provides a significant improvement in some cases.

### CODE REVIEW

**Comment by jlstevens** [comment]
Parser improvements, yay!

All I will ask is that you add a bunch of unit tests. There are already a [bunch here](https://github.com/ioam/holoviews/blob/master/tests/testparsers.py) but you cannot have too many parser tests.

**Comment by philippjfr** [comment]
Agreed, happy to add tests.

**Comment by philippjfr** [comment]
Added some tests now, which ended up helping me figure out further issues. Still not perfect but it actually let's you do a fair number of more complex expressions now.

**Comment by jlstevens** [comment]
Great to have more fixes and more tests! Merging.

**Pull request merged**
