### PR TITLE
Stripped metadata from bokeh element notebooks

### PR DESCRIPTION
**Pull request by jlstevens**
This PR aims to address #1617.

Here is the script I used:

```bash
#!/bin/bash
jq --indent 1 \
    '
    (.cells[] | select(has("outputs")) | .outputs) = []
    | (.cells[] | select(has("execution_count")) | .execution_count) = null
    | .metadata = {}
    | .cells[].metadata = {}
    ' $1 > /tmp/$(basename $1)
cat /tmp/$(basename $1) > $1
```

Note: This now clears *all* the notebook metadata, unlike the earlier versions of the script. I checked and the notebooks still work correctly.

Here is how I would clear the metadata from a directory:

```
for f in *.ipynb; do  strip_kernel.sh $f; done
```

### CODE REVIEW

**Comment by jlstevens** [comment]
It turns out that stripping out

```
"metadata": {
  "language_info": {
   "name": "python",
   "pygments_lexer": "ipython3"
  }
``

was not a good idea so I'll do this PR again. I guess I can just rebase once #2509 and redo the necessary commits.

**Comment by jlstevens** [comment]
Before I rebase, I'll build a list of notebooks that really do need the metadata stripped:

```
examples/gallery/demos/bokeh/autompg_violins.ipynb
examples/gallery/demos/bokeh/box_draw_roi_editor.ipynb
examples/gallery/demos/bokeh/iris_density_grid.ipynb
 examples/gallery/demos/bokeh/iris_grouped_grid.ipynb
 examples/gallery/demos/bokeh/irregular_quadmesh.ipynb
examples/gallery/demos/bokeh/nyc_radial_heatmap.ipynb
examples/gallery/demos/bokeh/point_draw_triangulate.ipynb
examples/gallery/demos/bokeh/route_chord.ipynb
examples/gallery/demos/matplotlib/autompg_violins.ipynb
examples/gallery/demos/matplotlib/iris_density_grid.ipynb
examples/gallery/demos/matplotlib/iris_grouped_grid.ipynb
examples/gallery/demos/matplotlib/irregular_quadmesh.ipynb
examples/gallery/demos/matplotlib/nyc_radial_heatmap.ipynb
examples/gallery/demos/matplotlib/route_chord.ipynb
examples/reference/elements/bokeh/Div.ipynb
examples/reference/elements/bokeh/QuadMesh.ipynb
examples/reference/elements/bokeh/RadialHeatMap.ipynb
examples/reference/elements/bokeh/Violin.ipynb
examples/reference/elements/matplotlib/QuadMesh.ipynb
examples/reference/elements/matplotlib/RadialHeatMap.ipynb
examples/reference/elements/matplotlib/VectorField.ipynb
examples/reference/elements/matplotlib/Violin.ipynb
examples/reference/features/bokeh/table_hooks_example.ipynb
examples/reference/streams/bokeh/BoxEdit.ipynb
examples/reference/streams/bokeh/PointDraw.ipynb
examples/reference/streams/bokeh/PolyDraw.ipynb
examples/reference/streams/bokeh/PolyEdit.ipynb
examples/topics/simulation/sri_model.ipynb
examples/user_guide/08-Gridded_Datasets.ipynb
```

**Comment by jlstevens** [comment]
None of these notebooks are tested so it doesn't make much sense to wait for the tests. Anyway, ready to review/merge. @philippjfr

**Comment by philippjfr** [comment]
Looks good, will merge right away since I can then get on with converting the reference notebook headers.

**Pull request merged**
