### PR TITLE
Ensure that Dataset.groupby does not sort by default

### PR DESCRIPTION
**Pull request by philippjfr**
Seemingly all the tabular data interfaces sorted the groups when applying a groupby, which is not always desirable, and is inconsistent with the gridded interfaces, which already maintain the supplied ordering. It also causes issues like https://github.com/ioam/holoviews/issues/2792, where the user expected the data to stay in the order it was defined in. While I think the previous behavior was incorrect I'm also somewhat wary of changing it right away since it is a definite change in behavior. Any thoughts @jbednar and @jlstevens?

- [x] Fixes https://github.com/ioam/holoviews/issues/2792

### CODE REVIEW

**Comment by jbednar** [comment]
I think it should change but at a fairly major release, so presumably 1.11?

**Comment by philippjfr** [comment]
That seems fine, I can fix #2793 by disabling sorting inside the plot, so we can fix the immediate issue and wait to merge this until the next major release.

**Comment by jlstevens** [comment]
> I think it should change but at a fairly major release, so presumably 1.11?

Agreed.

**Comment by philippjfr** [comment]
Now that we're working towards 1.11 I think we should just merge this now.

**Comment by philippjfr** [comment]
Merge?

**Pull request merged**
