### PR TITLE
Added span parameter for datashade operation

### PR DESCRIPTION
**Pull request by philippjfr**
Not sure ``span`` is the best name for this parameter but I just used the datashader argument name for now. Maybe ``clims`` or ``color_range`` would be better?

### CODE REVIEW

**Comment by jbednar** [comment]
I definitely don't like the name `span`.  Is `clims` already in use for this purpose in HoloViews?  If not it's more like a value_range.

**Comment by jlstevens** [comment]
I don't think ``clims`` would clash in this case and it is clearer/more intuitive than ``span``. Seems like the issue is that this isn't what this argument is called in datashader.

**Comment by philippjfr** [comment]
>Seems like the issue is that this isn't what this argument is called in datashader.

We already changed a bunch of the argument names because they're not very intuitive.

**Comment by jbednar** [comment]
The datashader API needs some tidying up before I'm ready to call it 1.0, so don't worry about what it's called in datashader.  I think HV should be supplying whatever dimension range it normally uses for non-datashader plots, though it could be convenient to provide an argument to `shade` that makes it simple to override that value when needed.

**Comment by jbednar** [comment]
@philippjfr, can you please rename `span` to whatever the best match to HoloViews usage is, and then make it respect the dimension's range if not overridden here?

**Comment by philippjfr** [comment]
>@philippjfr, can you please rename span to whatever the best match to HoloViews usage is, and then make it respect the dimension's range if not overridden here?

Was going to go with ``value_range`` and already have those changes applied locally. Will push in a minute.

**Comment by philippjfr** [comment]
Might go back to ``clims`` since it's shorter.

**Comment by jlstevens** [comment]
I also think ``clims`` is better:  this operation outputs and ``RGB`` so there is color mapping and from what I understand this parameter is really about controlling colors.

**Comment by jbednar** [comment]
clims is fine by me.  It's an edge case; the actual parameter has nothing to do with colors, and applies to the value rather than to any colors, but it has no effect on anything but colors, in the end.

**Comment by jlstevens** [comment]
Looks good to me and the tests are green. Merging.

**Pull request merged**
