### PR TITLE
Upgraded Travis versions to latest available

### PR DESCRIPTION
**Pull request by philippjfr**
Travis tests are failing atm, presumably because the version of libgfortran has changed.

### CODE REVIEW

**Comment by philippjfr** [comment]
Not sure I can fix this they updated the version from:

libgfortran:        3.0-0     

to:

libgfortran:        3.0.0-1 

And I can't seem to find a way to pin it to the older version.

**Comment by philippjfr** [comment]
That also doesn't work we're still getting this error:

```
ImportError: numpy.core.multiarray failed to import
```

May have to raise the issue with the conda team.

**Comment by philippjfr** [comment]
So this was a complete nightmare, but I finally figured out the problem. The travis python virtualenv has a version of numpy that it's been linking to, if you delete that it works again. Just need to find a clean way to do so now.

**Comment by philippjfr** [comment]
Hooray it's finally working. This PR updates our travis setup from:

matplotlib 1.4.3 -> matplotlib-1.5.1
numpy 1.9.3 -> numpy 1.10.4

Hopefully this will also get rid of all the transients we were experiencing. Ready to merge once the PR build passes fully.

**Comment by jlstevens** [comment]
Yay. Being tied to old versions of numpy/matplotlib was a pain.

I really hope it *does* fix the transients as well...

**Comment by philippjfr** [comment]
Sorry to disappoint, already seen a transient. Still glad we're no longer tied to the old versions.

**Comment by philippjfr** [comment]
PR build passed at last, please merge.

**Comment by jlstevens** [comment]
Oh well. As you say, at least something good came out of this...

**Pull request merged**
