### PR TITLE
Updated bokeh version used on travis

### PR DESCRIPTION
**Pull request by jlstevens**
Updates the bokeh version in travis.yml.

### CODE REVIEW

**Comment by jlstevens** [comment]
This PR could also pin IPython (to avoid the bad exception problem) and matplotlib. We just need to be confident that the pinning is appropriate.

**Comment by philippjfr** [comment]
I think we should go ahead with this and upgrade IPython and matplotlib as well.

**Comment by jlstevens** [comment]
For reference, the matplotlib version that appears to be specified in the ``.travis.yml`` is matplotlib=2.1.2.

**Comment by jlstevens** [comment]
Tests are updated and now green. Merging.

**Pull request merged**
